### ISSUE TITLE
Run Sync on start

### ISSUE THREAD

**Issue by mercplus** [bakito/adguardhome-sync#10]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When the docker container starts, initiate the sync function. 

**Describe alternatives you've considered**
I had to reduce the sync frequency if I was making changes.

**Additional context**
I ideally would want to keep the sync for 60 mins. If my server starts before the 60 mins cron job, I lose 1 sync. This would also help with testing changes.

**Comment by bakito** [comment]
Hi @mercplus 

Thank you for this request.
Actually this was also in my mind.

I added it to https://github.com/bakito/adguardhome-sync/releases/tag/v0.2.0
