### ISSUE TITLE
Syncing more/most/all settings like DNS Settings & DHCP Settings

### ISSUE THREAD

**Issue by MarsWarrior** [bakito/adguardhome-sync#12]
**Is your feature request related to a problem? Please describe.**

I would like to have full replica's of several AGH instances.
The current replication does not yet replicate the DNS Settings (Settings->DNS) and DHCP settings for instance. This means I still have to manually configure multiple AGH instances and manually keep them in sync.

**Describe the solution you'd like**

Either a full replica, or selectable replication settings. I have no idea if it would be a problem for some people if a replica is a full replica of the origin instance.

**Describe alternatives you've considered**

Manual sync is not an option regarding DHCP settings. Error prone...

**Additional context**

None.

**Comment by bakito** [comment]
Hi

I started wit the implementation of dns.
I've got one question about dhcp.
Is it ok to replicate dzcp settings and have mor than one dhcp running in one network?

**Comment by MarsWarrior** [comment]
If you look at this serverfault question about "[Can I have multiple DHCP servers on one network?](https://serverfault.com/questions/368512/can-i-have-multiple-dhcp-servers-on-one-network)", you see that this is no problem as long as you follow some rules.

If you wanna use DHCP reservations, like I do, there is absolutely no problem in having multiple DHCP servers, as the first one 'wins' and returns the answer to the client. In this case however it is very important to keep the reservations in sync. Hence my request 😄 

Some others use a split scope solution, ie the first DHCP server serves the .100-.150 range and the second the .151-.200 range in the same subnet. This is mostly advised if not using DHCP reservations.

I hope that clarifies your question!

So I use AGH for:
- DNS rewrites assign a subdomain to a static IP address (already covered by adguardhome-sync)
- The DHCP server uses reserverations for each device/computer om my network. (this feature requestg)

This means I can address all devices with a specific subdomain.

**Comment by bakito** [comment]
Hi @MarsWarrior 

I implemented a first rc with the new features.
https://github.com/bakito/adguardhome-sync/releases/tag/v0.3.0-rc1

The new features are currently not enabled by default.

you can enable them by adding the arg `--beta dns,dhcp` or with env variable `BETA=dns,dhcp`

I'm not done with writing all the unit tests, but wanted to give you the opportunity to test the features before I make the release.

Please let me know if the features cover your use-cases.

KR,
Marc

**Comment by AmoebeLabs** [comment]
Great!

Are you able to push a docker image to quay.io/bakito/adguardhome-sync ?
I'm using docker 😄

I see there is a new image just pushed with the label "main", but I doubt that is the RC version?

**Comment by MarsWarrior** [comment]
Oops, forgot to sign in as me on this computer 😊

**Comment by MarsWarrior** [comment]
Well, sofar, so good:

```
2021-05-29T08:20:39.302Z	INFO	sync	sync/sync.go:48	Setup cronjob	{"version": "v0.3.0-rc1", "cron": "*/10 * * * *"}
2021-05-29T08:20:39.302Z	INFO	sync	sync/sync.go:56	Run on startup	{"version": "v0.3.0-rc1"}
2021-05-29T08:20:40.244Z	INFO	sync	sync/sync.go:181	Start sync	{"from": "192.168.2.190", "to": "192.168.2.191"}
2021-05-29T08:20:41.096Z	INFO	client	client/client.go:416	Set dns config list	{"host": "192.168.2.191"}
2021-05-29T08:20:41.345Z	INFO	client	client/client.go:427	Set dhcp server config	{"host": "192.168.2.191"}
2021-05-29T08:20:41.418Z	INFO	client	client/client.go:433	Add static dhcp lease	{"host": "192.168.2.191", "mac": "00:12:7d:42:aa:08", "ip": "192.168.2.208", "hostname": "test.server.local"}
2021-05-29T08:20:41.490Z	INFO	sync	sync/sync.go:241	Sync done	{"from": "192.168.2.190", "to": "192.168.2.191"}
2021-05-29T08:20:41.490Z	INFO	sync	sync/http.go:65	Starting API server	{"version": "v0.3.0-rc1", "port": 8080}
```

I will check some more items, as I did some manual syncing for DNS settings, but sofar I can see that:

- DHCP settings are copied
- DHCP static leases are copied

**Comment by MarsWarrior** [comment]
I can't get REPLICA1 to sync. Is that a bug, or am I doing something wrong 😄 
So:
- REPLICA_* works
- REPLICA1_* does not sync at all

**Comment by bakito** [comment]
Actually, this should work.
I do my local tests also with REPLICA1

`
REPLICA1_URL=http://localhost:9091
REPLICA1_USERNAME=username
REPLICA1_PASSWORD=1234567890
REPLICA1_AUTOSETUP=true
BETA=dhcp,dns
`

Whats your docker config?

**Comment by MarsWarrior** [comment]
Aaahhrggg. I checked Portainer, and saw a typo in the _URL part, it had a “:” added bedore the “=“ !

I removed the “:”, and now the second replica syncs too!

i overlooked that typo in the compose file a million times, but saw it immediately in Portainer 😄

**Comment by gravyflex** [comment]
> Hi @MarsWarrior
> 
> I implemented a first rc with the new features.
> https://github.com/bakito/adguardhome-sync/releases/tag/v0.3.0-rc1
> 
> The new features are currently not enabled by default.
> 
> you can enable them by adding the arg `--beta dns,dhcp` or with env variable `BETA=dns,dhcp`
> 
> I'm not done with writing all the unit tests, but wanted to give you the opportunity to test the features before I make the release.
> 
> Please let me know if the features cover your use-cases.
> 
> KR,
> Marc
`
 you can enable them by adding the arg `--beta dns,dhcp` or with env variable `BETA=dns,dhcp``

Could you put this in a more prominent place on the Readme? It took me far too long to find the setting to enable DNS sync.

Thanks for this cool software!

**Comment by bakito** [comment]
dns and dhcp are now added to default sync. beta removed.

https://github.com/bakito/adguardhome-sync/releases/tag/v0.3.0
