### ISSUE TITLE
adguardhome-sync executable Windows keeps getting deleted/reported by Windows Defender as malware 

### ISSUE THREAD

**Issue by hawkeye73** [bakito/adguardhome-sync#124]
The executable keeps getting deleted:

Trojan:Win32/Sabsik.EN.A!ml
Trojan:Win32/Trickbot!ml
Trojan:Win32/Wacatac.H!ml

What to do?

Is it a false positive? As it constant changes....

**Comment by bakito** [comment]
@hawkeye73 please check version https://github.com/bakito/adguardhome-sync/releases/tag/v0.4.10 where windows binaries are not compressed with upx.

**Comment by hawkeye73** [comment]
Thanks! appreciated
