### ISSUE TITLE
Double quotes around username/password prevents syncing

### ISSUE THREAD

**Issue by MarsWarrior** [bakito/adguardhome-sync#13]
**Describe the bug**
If the username or password has double quotes in the compose definition, syncing fails as if the wrong username/password is specified for the replica

**To Reproduce**
1. What version of AdGuardHome sync used?
2. What version of AdGuardHome us used?
3. How does the configuration look?
4. What is the error message?

Using version 0.2 of sync with AGH 105.2

```yaml
environment:
  - REPLICA_USERNAME="username"
  - REPLICA_PASSWORD="password"
```
The errormessage is a 404, invalid username/password.

**Expected behavior**
Syncing works, independent of single/double quotes used for username/password

If I remove the quotes, syncing works as expected.

**Screenshots**
If applicable, add log files or json responses from AdGuardHome to help explain your problem.

**Additional context**

**Comment by bakito** [comment]
This is correct and is caused by docker-compose.

If you define the environment variables in array form the are uses in the container as is, with the quotes. 
The single variables in the array are not yaml

```yaml
environment:
  - REPLICA_USERNAME="username"
  - REPLICA_PASSWORD="password"
```

If you define the environment variables as yaml map, single or double quotes  are not propagated to the container.


```yaml
environment:
  REPLICA_USERNAME: "username"
  REPLICA_PASSWORD: 'password'
```

**Comment by MarsWarrior** [comment]
Ah you'r right. I usually use the map format, but for some reason not in this case...

Thanx for the clarification!
