### ISSUE TITLE
GitHub Sponsor or Donation Link

### ISSUE THREAD

**Issue by fanuch** [bakito/adguardhome-sync#135]
Finally found time to run this and the features as well as the documentation was great and easy to follow!

I would like to show my appreciation with a small token of gratitude. 

Could you consider setting up [GitHub Sponsor](https://github.com/sponsors) on this repo or one of the other donation platforms?

**Comment by bakito** [comment]
@fanuch thank you very much for the nice feedback. Much appreciated!

I'm working in Sponsorship setup and will keep you updated.

**Comment by bakito** [comment]
@fanuch I was approved for github Sponsorship
The button should now be available on the repo.
