### ISSUE TITLE
Filters are synced but not enabled status

### ISSUE THREAD

**Issue by Cerothen** [bakito/adguardhome-sync#140]
**Describe the bug**
Filters are synced from the primary to secondary instance successfully. The "enabled" status is not, in my case I have 2 disabled blocklists that were synced over to the second instance however on the second instance they were enabled.

**To Reproduce**
1. What version of AdGuardHome sync used? 0.4.11
3. What version of AdGuardHome us used? v0.107.21
4. How does the configuration look? Default, all syncs enabled
5. What is the error message? No error message, just doesn't set the enabled statuses

**Expected behavior**
The filter lists get synced over as well as the status of those lists (enabled/disabled)

**Log Files**
N/A

**Additional context**
N/A

**Comment by bakito** [comment]
@Cerothen I'm not able to reproduce the issue you describe with the same version.
Please provide more information.
Which filters? block-/allowlist?

Are origin and replica of the same version?

Please enable debug logs for adguardhome-sync by defining the env variable LOG_LEVEL=debug and provide the debug logs to this issue.


Thank you

**Comment by bakito** [comment]
Adguardhome does not enable new filter lists if they are offline. Is the Filter that is not enabled offline?

**Comment by Cerothen** [comment]
No the sync completes successfully and all the lists from the origin instance are moved to the secondary instances successfully.

In the AdGuardHome.yaml the filters have a key called "enabled" which corresponds to a checkbox in the first column of the filters list in the UI. If a list is disabled it isn't reflected on secondary I stances

**Comment by Cerothen** [comment]
Apparently it's only for the initial sync, updates seem to be caught after that

**Comment by dhenry437** [comment]
If I could reopen this, it's not really the first sync, it's the first sync for each blocklist. As in:

Origin: Add a new blocklist, untick to disable
Sync
Remote: New blocklist appears, but is enabled
Sync
Remote: Blocklist is now disabled

Maybe the check for enabled status is getting skipped if the blocklist is new?

**Comment by bakito** [comment]
@dhenry437 can you please open a new issue and provide proper information, such as logs, config,  version, ...

Without this information there's not much I can do.

Thank you
