### ISSUE TITLE
ERROR: http: server gave HTTP response to HTTPS client

### ISSUE THREAD

**Issue by geoffrothman** [bakito/adguardhome-sync#144]
**Describe the bug**
running 'adguardhome-sync run' gives me the error "http: server gave HTTP response to HTTPS client"

**To Reproduce**
1. What version of AdGuardHome sync used? adguardhome-sync version devel
2. What version of AdGuardHome us used? Version: 
v0.107.22
3. How does the configuration look? out of the box (https is not turned on)
4. What is the error message?
5.  ERROR   sync    sync/sync.go:104        Error getting origin status     {"from": "10.0.0.50:3000", "error": ": Get \"https://10.0.0.50:3000/control/status\": http: server gave HTTP response to HTTPS client"}

**Expected behavior**
that the sync would work?

**Log Files**
$ adguardhome-sync run
INFO    sync    sync/sync.go:29 AdGuardHome sync        {"version": "devel", "build": "N/A"}
INFO    sync    sync/http.go:52 Starting API server     {"port": 8080}
INFO    sync    sync/sync.go:65 Running sync on startup
DEBUG   client  client/client.go:139    do get  {"host": "10.0.0.50:3000", "method": "GET", "path": "status", "username": "admin"}
2023-01-29T02:26:56.756-0600    
DEBUG   client  client/client.go:148    error in do get {"host": "10.0.0.50:3000", "method": "GET", "path": "status", "username": "admin", "status": 0, "body": "", "error": "Get \"https://10.0.0.50:3000/control/status\": http: server gave HTTP response to HTTPS client"}
ERROR   sync    sync/sync.go:104        Error getting origin status     {"from": "10.0.0.50:3000", "error": ": Get \"https://10.0.0.50:3000/control/status\": http: server gave HTTP response to HTTPS client"}
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
        /root/go/pkg/mod/github.com/bakito/adguardhome-sync@v0.4.11/pkg/sync/sync.go:104
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func3
        /root/go/pkg/mod/github.com/bakito/adguardhome-sync@v0.4.11/pkg/sync/sync.go:66

**Additional context**

**Comment by bakito** [comment]
Please provide the adguardhome-sync configuration you applied

**Comment by bakito** [comment]
@geoffrothman I can not provide you any support if you do not provide your configuration values.
