### ISSUE TITLE
Sync all DHCP settings, but do not enable it

### ISSUE THREAD

**Issue by tapufd** [bakito/adguardhome-sync#155]
Hi,
Is it possible to sync all DHCP settings, but do not enable the DHCP server on the REPLICA?
Currently it syncs all settings now, which is good, but it also enables the DHCP server on the REPLICA, which is not good, as it is not wise to have more then 1 running DHCP server on your LAN. (if they don't know from each other)
Thx, T

**Comment by bakito** [comment]
Currently there's only the option to sync or not sync DHCP Settings.

**Comment by bartclone** [comment]
Seems logical.

I wonder, @tapufd @bakito , why a should another instance even accept dhcpd-settings, when it is enabled on that instance? 
As it’s always a one-way sync/transfer.

**Comment by tapufd** [comment]
If I disable the DHCP server on the REPLICA (how it should be as it is enabled on the ORIGIN), and a sync is done from ORIGIN to REPLICA, the DHCP server is again enabled on the REPLICA.
This should be avoided, as no 2 DHCP servers should be running on the same LAN.
That is why I would prefer an option to sync the DHCP settings, but not enable DHCP on the REPLICA.
I have a master-standby setup running, so if the ORIGIN (master) is having issues, I can activate the REPLICA (standby) one.

**Comment by bartclone** [comment]
> If I disable the DHCP server on the REPLICA (how it should be as it is enabled on the ORIGIN), and a sync is done from ORIGIN to REPLICA, the DHCP server is again enabled on the REPLICA. This should be avoided, as no 2 DHCP servers should be running on the same LAN. 

I think you are searching for some fail-over solution?

If not, maybe you can explain a bit clearly what the problem/scenario is you want to solve?

>That is why I would prefer an option to sync the DHCP settings, but not enable DHCP on the REPLICA. I have a master-standby setup running, so if the ORIGIN (master) is having issues, I can activate the REPLICA (standby) one.

It's fine to run 2 DHCP servers.
Not an very usual setup, but certainly not forbidden.

However, DNS and DHCP in itself do not need fail-over that enables a replica when the origin fails.
DNS has its own way (as in: specify at least 2 DNS-addresses) and DHCPd uses Discovery/DORA-principle

Also: there is always (only) one origin and one (or more) AGH replica's.
It's a one-way sync; so even in the case (only) the replica becomes active, the origin=previous DHCPd will be in the dark anyway.

**Comment by tapufd** [comment]
I use keepalived to move a certain IP between an active-passive setup.
That IP has certain services linked to it:
* DNS (AdGuard Home)
* stunnel
* ...
If the active node goes down, that IP goes to the passive node and handles services there.
However DHCP (also provided by AGH) cannot be linked to that IP, and uses the local IP of the node.
So I have a script that is triggered by keepalived, that can enable/disable DHCP from AGH (via REST API) on the corresponding node.
But like I said, the sync of the DHCP settings overwrites my DHCP-enabled setting on the REPLICA.
Having 2 DHCPs on the same LAN is not recommended, as both can hand out the same ip-adresses to different devices on the LAN, as they are not aware of eachother.
This leads to duplicate IP situations.

**Comment by tapufd** [comment]
ok, np, will look for another solution then.

**Comment by bartclone** [comment]
> ok, np, will look for another solution then.

Oh well, a PR implementing your issue might get accepted ;)
Or if @bakito sees a fit to implement

**Comment by tapufd** [comment]
Cool, many thanks!
Will test it asap and give some feedback here...

**Comment by tapufd** [comment]
I just realize that I use the config file setup:
# replica instance (optional, if only one)
replica:
  # url of the replica instance
  url: http://x.x.x.x
  # apiPath: define an api path if other than "/control"
  insecureSkipVerify: true # disable tls check
  username: ***
  password: ***
  interfaceName: eth0

What you mention above is for the docker compose file, I assume?
How does this fit in my config file setup?
Just add "DHCPSERVERENABLED: false" under replica?
Thx!

**Comment by bakito** [comment]
Its `dhcpServerEnabled` under replica.

**Comment by tapufd** [comment]
It works like a charm!
Many, many thanks for implementing this!

**Comment by bakito** [comment]
Yes, there will be a new release

**Comment by bakito** [comment]
released in https://github.com/bakito/adguardhome-sync/releases/tag/v0.4.13

**Comment by divemasterjm** [comment]
> released in https://github.com/bakito/adguardhome-sync/releases/tag/v0.4.13

i'm trying to disable dhcp activation but i'm not able, can you please tell me where to add     dhcpServerEnabled: false?
i've tried under replicas but got an error, under features does nothing

thanks in advance

**Comment by bakito** [comment]
Please check the readme.

```
features:
  ...
  dhcp:
    serverConfig: true
    staticLeases: true
```

**Comment by divemasterjm** [comment]
> dhcpServerEnabled: false

i did but im talking about the dhcpServerEnabled: false entry

**Comment by bakito** [comment]
there's an example in the test files: https://github.com/bakito/adguardhome-sync/blob/4a62b80e7514e2d28c78c84d9499ac2f7ebbfdf6/testdata/config_test_replica.yaml#L18

**Comment by divemasterjm** [comment]
Sorry, my bad
Thanks
