### ISSUE TITLE
Running Sync  Windows 

### ISSUE THREAD

**Issue by kylelliott** [bakito/adguardhome-sync#170]
i can run the script on windows fine but wont close on it own also tying to use task scheduler to auto run and cant ge that work either please see scrren 
![image](https://user-images.githubusercontent.com/23058718/226483452-8934257a-2cd1-4671-9256-0e2ad9c341d2.png)

**Comment by bakito** [comment]
Hi @kylelliott 

can you please provide your configuration of agh-sync and the Debug Log?

thx

**Comment by kylelliott** [comment]
![image](https://user-images.githubusercontent.com/23058718/226561442-cbe0734d-6048-4887-987b-4d05003b6439.png)

Where or how do i get the debug log

**Comment by bakito** [comment]
Debug level is enabled via env varaible. See https://github.com/bakito/adguardhome-sync#log-level

If you want to command to terminate after the sync, try disabling the api server by setting the followind env variable:
`API_PORT=0`

**Comment by bakito** [comment]
did you use `set API_PORT=0` as it is windows?

**Comment by kylelliott** [comment]
that work now what i need to setup it up in task scheduler to Auto run and what is best  options

**Comment by bakito** [comment]
I'm sorry bit I can't help you with that, as I don't know how this is done best in Windows

**Comment by kylelliott** [comment]
ok no worrries  thanks for your help today
