### ISSUE TITLE
Syncing of dhcpv4 options array and local_domain_name in the AdGuardHome.yaml

### ISSUE THREAD

**Issue by Wob76** [bakito/adguardhome-sync#174]
Hi,

I'm new to adguardhome-sync, I've been running adguard as my DHCP\DNS solution for awhile in a docker on my NAS, I'm wanting to build up a 2nd instance on a Pi Zero W for load balancing and failover during maintenance on my NAS.

I have sync installed and working, but I have an option 6 set in my dhcpv4 settings to configure a primary and secondary DNS, but this array seems to be synchronised over empty.

Origin Server:
  dhcpv4:
    gateway_ip: 192.168.0.1
    subnet_mask: 255.255.255.0
    range_start: 192.168.0.1
    range_end: 192.168.0.100
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options:
      - 6 ips 192.168.0.1,192.168.0.2

Replica:
  dhcpv4:
    gateway_ip: 192.168.0.1
    subnet_mask: 255.255.255.0
    range_start: 192.168.0.1
    range_end: 192.168.0.100
    lease_duration: 86400
    icmp_timeout_msec: 1000
    options: []

I have also noticed that 'local_domain_name:' is not synchronised, I have customised mine from the default "lan" on my Origin Server but the sync writes it as 'lan' on the replica during a sync.

Thanks

**Comment by bakito** [comment]
@Wob76 Thank you for your request.

Can you help me, how do you set these options in the dhcp config?
I can not find them in the web interface.

**Comment by bakito** [comment]
This feature is not implemented in the API of AdguardHome

Supported Attributes are here: https://github.com/AdguardTeam/AdGuardHome/blob/master/internal/dhcpd/http_unix.go#L20

If it is not supported by the API of AdguardHome, there is no chance to sync this with adguardhome-sync.

Sorry for that

**Comment by Wob76** [comment]
No Problem, thanks for looking into it, both are "advanced" options that you need to set in the AdGuardHome.yaml file. They are documented in the AdGuard Wiki, but I guess being outside the GUI they are not part of the API.

For the moment I decided to let the DHCP config seed and then turn off the sync for that while keeping the leases in sync, this let me change to scope for DHCP to ensure no non-reserved leases are granted from both instances and enables me to tweak the other settings.
