### ISSUE TITLE
Continue on Error

### ISSUE THREAD

**Issue by peterhanzlik** [bakito/adguardhome-sync#179]
Hi,

when the sync at some item crashes (e.g. blocklist is obsolete and cannot be access any longer). the tool crashes and does not process any item further. It would be great if the tool will just throw an error for items that could not have been synced and continued to sync the other items.

Example:
`2023-04-08T10:23:30.921Z	ERROR	sync	sync/sync.go:241	Error syncing filters	{"from": "synology.lan:8081", "to": "loxberry.lan:8081", "error": "400 Bad Request(Couldn't fetch filter from url https://raw.githubusercontent.com/AdguardTeam/FiltersRegistry/master/filters/filter_2_English/filter.txt: got status code 404, want 200\n)"}
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).syncTo
	/home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:241
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
	/home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:186
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).handleSync
	/home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/http.go:31
github.com/gin-gonic/gin.(*Context).Next
	/home/bakito/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.CustomRecoveryWithWriter.func1
	/home/bakito/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/recovery.go:102
github.com/gin-gonic/gin.(*Context).Next
	/home/bakito/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/context.go:174
github.com/gin-gonic/gin.(*Engine).handleHTTPRequest
	/home/bakito/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:620
github.com/gin-gonic/gin.(*Engine).ServeHTTP
	/home/bakito/go/pkg/mod/github.com/gin-gonic/gin@v1.9.0/gin.go:576
net/http.serverHandler.ServeHTTP
	/home/bakito/.gimme/versions/go1.20.1.linux.amd64/src/net/http/server.go:2936
net/http.(*conn).serve
	/home/bakito/.gimme/versions/go1.20.1.linux.amd64/src/net/http/server.go:1995`

**Comment by bakito** [comment]
@peterhanzlik Thank you for your request.
I would have to think of a way to properly implement this.

**Comment by bakito** [comment]
A refactoring has stared after which this should be possible: https://github.com/bakito/adguardhome-sync/tree/sync-actions

**Comment by bakito** [comment]
implemented in https://github.com/bakito/adguardhome-sync/releases/tag/v0.5.4
