### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by Ryonez** [bakito/adguardhome-sync#185]
**Describe the bug**
AdGuard sync reports that the valid letsencrypt cert in use is signed by unknown authority.

**To Reproduce**
1. What version of AdGuardHome sync used? 0.4.14 (Docker: lscr.io/linuxserver/adguardhome-sync)
2. What version of AdGuardHome us used? 
v0.107.29 (Docker: https://registry.hub.docker.com/r/adguard/adguardhome)
3. How does the configuration look?
It appears to be solid, I'm connecting with my browser and the cert is reported as good:
![image](https://user-images.githubusercontent.com/16157130/235344840-ba8ba7c1-52f8-4709-8125-007ced1aacdf.png)
4. What is the error message?

<details>
<summary>Sync log</summary>

```txt
2023-04-30T20:57:52.288+1200	INFO	root	cmd/root.go:122	Using config file:/config/adguardhome-sync.yaml
2023-04-30T20:57:52.289+1200	INFO	sync	sync/sync.go:35	AdGuardHome sync	{"version": "0.4.14", "build": "2023-04-12T18:31:45Z", "os": "linux", "arch": "amd64"}
2023-04-30T20:57:52.289+1200	INFO	sync	sync/sync.go:62	Setup cronjob	{"cron": "*/10 * * * *", "next-execution": "2023-04-30T21:00:00.000+1200"}
2023-04-30T20:57:52.290+1200	INFO	sync	sync/http.go:52	Starting API server	{"port": 8080}
2023-04-30T20:57:52.290+1200	INFO	sync	sync/sync.go:72	Running sync on startup
2023-04-30T20:57:52.494+1200	ERROR	sync	sync/sync.go:111	Error getting origin status	{"from": "adguard-15.alteria.xyz", "error": ": Get \"https://adguard-15.alteria.xyz/control/status\": tls: failed to verify certificate: x509: certificate signed by unknown authority"}
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
	/home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:111
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func3
	/home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:73
```

</details>

**Expected behavior**
That sync connects fine

**Log Files**
Logs added above, can provide more if needed

**Additional context**
I've tried this with the docker container made here: ghcr.io/bakito/adguardhome-sync:latest
Same results.

**Comment by bakito** [comment]
Hi 

the image scr.io/linuxserver/adguardhome-sync is not maintained by this repository/me.

Dies the issue also consist if you used the images from this repo?
https://github.com/bakito/adguardhome-sync/pkgs/container/adguardhome-sync

**Comment by Ryonez** [comment]
Yes, I mentioned that under the additional context.
The docker images seem interchangeable, so I've left this repo's one in place as this is figured out.

**Comment by bakito** [comment]
Sorry, I didn't see that.
It might be, that lets encrypt uses a new ca cert that is not yet available in the base images used.

I rebuilt the latest image to use the newest base.
Can you try this image if it works.

Otherwise you can either configure the replica to use `insecureSkipVerify=true` ( or env REPLICA_INSECURESKIPVERIFY=true) to temporary ignore the cert.

Our you can mount the valid cert as volume to your container with path /etc/ssl/certs/ca-certificates.crt

**Comment by Ryonez** [comment]
I used the main tag as that has was built in the last hour, compared to latest which is 18 days. No joy.

I hadn't noticed the `insecureSkipVerify: true` flags, set them up and it's working with that currently.
I'll stick around though to get the TLS going properly.
