### ISSUE TITLE
Question: Main vs Synced

### ISSUE THREAD

**Issue by HPMSGEN8** [bakito/adguardhome-sync#186]
Good Day

I do not know where to ask this.

I had to use my Replica due to the fact the main container broke. Now i have installed another copy on the latest version.

This time i am seeing all the DNS Queries and all states get synced over is this all correct ?

They both running v0.107.29

Thanks

**Comment by bakito** [comment]
Hi 

If I'm understanding this correct, you should change origin <-> reolica in order to sync your settings from the old replica to the new instance.

**Comment by HPMSGEN8** [comment]
I think i found my issue so closing :)
