### ISSUE TITLE
Safe Search Provider selection not syncing

### ISSUE THREAD

**Issue by BombusAlpinus** [bakito/adguardhome-sync#200]
**Describe the bug**
Sync of Safe Search Providers does not work.
Toggle of SafeSearch at all is syncing.

**To Reproduce**
General Settings --> Use Safe Search --> disable one or more of the search providers

**Expected behavior**
Sync should also include the selection of the search providers

**Comment by bakito** [comment]
Implemented in https://github.com/bakito/adguardhome-sync/releases/tag/v0.5.0
