### ISSUE TITLE
Sync "Pause service blocking schedule"

### ISSUE THREAD

**Issue by Skynet2029** [bakito/adguardhome-sync#234]
It would be great if the "Pause service blocking schedule" could be synchronized.

Filters -> Blocked services -> Pause service blocking card

<img width="962" alt="Screenshot 2023-11-12 at 8 35 55" src="https://github.com/bakito/adguardhome-sync/assets/419102/ff8e1e0f-39fe-4c1b-9b59-c3befc45333a">

Settings -> Client settings -> Edit Client -> Pause service blocking tab

<img width="629" alt="Screenshot 2023-11-12 at 8 38 16" src="https://github.com/bakito/adguardhome-sync/assets/419102/3433c060-f122-4568-8170-5eb429cab454">

That would be great. Thank you.

**Comment by bakito** [comment]
Hi @djak250 
Thank you for the request.

I'm currently refactoring the Application to use to use the openapi interface against adguardhome.
This should help for future new features.

I'ts quite some work to refactor, so will only implement new features in the refactored version.

**Comment by bakito** [comment]
Implemented in https://github.com/bakito/adguardhome-sync/releases/tag/v0.5.0
