### ISSUE TITLE
no route to host

### ISSUE THREAD

**Issue by dlsnet** [bakito/adguardhome-sync#24]
I'm getting bellow error. Could you please help to work around? Thank you.

2021-06-12T19:21:53.750Z	INFO	sync	sync/http.go:65	Starting API server	{"version": "v0.3.0-rc1", "port": 8080},
2021-06-12T19:22:55.636Z	INFO	root	cmd/root.go:102	Using config file:/config/adguardhome-sync.yaml,
2021-06-12T19:22:55.638Z	INFO	sync	sync/sync.go:48	Setup cronjob	{"version": "v0.3.0-rc1", "cron": "*/10 * * * *"},
2021-06-12T19:22:55.639Z	INFO	sync	sync/sync.go:56	Run on startup	{"version": "v0.3.0-rc1"},
2021-06-12T19:22:56.520Z	INFO	sync	sync/sync.go:181	Start sync	{"from": "192.168.20.197:80", "to": "192.168.20.73:80"},
2021-06-12T19:22:59.573Z	ERROR	sync	sync/sync.go:185	Error getting replica status	{"from": "192.168.20.197:80", "to": "192.168.20.73:80", "error": "Get \"http://192.168.20.73:80/control/status\": dial tcp 192.168.20.73:80: connect: no route to host"},
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).syncTo,
	/go/src/app/pkg/sync/sync.go:185,
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync,
	/go/src/app/pkg/sync/sync.go:168,
github.com/bakito/adguardhome-sync/pkg/sync.Sync,
	/go/src/app/pkg/sync/sync.go:57,
github.com/bakito/adguardhome-sync/cmd.glob..func1,
	/go/src/app/cmd/run.go:23,
github.com/spf13/cobra.(*Command).execute,
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:852,
github.com/spf13/cobra.(*Command).ExecuteC,
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960,
github.com/spf13/cobra.(*Command).Execute,
	/go/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897,
github.com/bakito/adguardhome-sync/cmd.Execute,
	/go/src/app/cmd/root.go:60,,
n,
	/go/src/app/main.go:6,
runtime.main,
	/usr/local/go/src/runtime/proc.go:225,
2021-06-12T19:22:59.573Z	INFO	sync	sync/http.go:65	Starting API server	{"version": "v0.3.0-rc1", "port": 80},

**Comment by Stuke00** [comment]
Same error for me.  Any resolution found yet?

**Comment by bakito** [comment]
Are AGH and the Sync pod running in the same dicker instance?
Are they allowed to connect?

Sounds Like a connectivity issue to me

**Comment by Stuke00** [comment]
Sync is on a docker, AdGuard is in a raspberry Pi

**Comment by bakito** [comment]
It seems the docker container is not allowed to do the connection.
This would be an issue with docker and not this tool

**Comment by Stuke00** [comment]
I figured it out, I had to put a / at the end of my IP address.

**Comment by bakito** [comment]
for which IP did you have to do that?
Can you share your configuration?

I'd like to be able to reproduce this.

**Comment by Stuke00** [comment]
I don’t recall which one needed it, I think it was the replica but I have it on both now

# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "*/10 * * * *"

origin:
  # url of the origin instance
  url: http://10.20.30.153/
  # apiPath: define an api path if other than "/control"
  insecureSkipVerify: true # disable tls check
  username:
  password:

# replica instance (optional, if only one)
replica:
  # url of the replica instance
  url: http://10.20.30.151/
#  username: 
#  password:

# replicas instances (optional, if more than one)
#replicas:
  # url of the replica instance
#  - url: http://192.168.1.4
#    username: username
#    password: password

# Configure the sync API server, disabled if api port is 0
api:
  # Port, default 8080
  port: 8080
  # if username and password are defined, basic auth is applied to the sync API 
  #username: username
  #password: password

**Comment by bakito** [comment]
Have you tried to get more info from debug mode by setting env var LOG_LEVEL=debug ?

**Comment by Citizen3rased** [comment]
I just figured it out.. kind of. The problem seemed to be adguard-sync being on a custom docker network. I have the origin instance running on a pi, while the replica was on the same unraid host as the sync docker, but on br0 network with it's own IP. I'm not sure why adguard sync can't access it though, since it has it's own IP and is accessible from other devices on the network. Is it expected that adguard-sync must be run on br0 or host network?

**Comment by Citizen3rased** [comment]
To clarify, all I changed was Adguard-sync from custom docker bridge network to br0 network and gave it it's own IP and suddenly it could communicate fine with the 192.168.1.64:80 adguard instance, running on unraid br0 as well.

**Comment by nayab9** [comment]
> To clarify, all I changed was Adguard-sync from custom docker bridge network to br0 network and gave it it's own IP and suddenly it could communicate fine with the 192.168.1.64:80 adguard instance, running on unraid br0 as well.

Thank you very much for this fix. I had the exact same issue and this resolved it.

Setup with failure:

```
Adguard 1 on Unraid 1 network: br0
Adguard 2 on Unraid 2 network: br0

Adguard-sync on Unraid 2 network: bridge
```

Once I changed adguard-sync on Unraid 2 from `bridge -> br0`, it works with no other changes required.

Must have something to do with traversal between br0 and bridge?

**Comment by xbmcnut** [comment]
I'm getting the same error after deploying this evening.
```
ERROR	sync	sync/sync.go:104	Error getting origin status	{"from": "10.0.1.2", "error": ": Get \"http://10.0.1.2/control/status\": dial tcp 10.0.1.2:80: connect: no route to host"}
```
My (master) instance is on the same host but set up as a macvlan on 10.0.1.2 with the host IP of the NAS as 10.0.1.100. Now I understand that in order for the host to be able to reach the macvlan, you need to create a bridge network. I did that using the instructions [here](https://www.wundertech.net/how-to-install-adguard-home-on-a-synology-nas/ ) and that has now at least allowed by Homer instance (same docker host) to access AGH on 10.0.1.2 but sadly, I still get an error from AGHS as above.

**Comment by xbmcnut** [comment]
I just fixed my issue by adding my AGH docker container to the bridge network created by AG-Sync (adguard-sync_default) and then changing the AG-sync config for my primary DNS server to the docker IP (172.20.0.2). Probably not the best way to do it but it works.

**Comment by xbmcnut** [comment]
I've updated my methodology after watching many hours of docker networking videos. Seems with a custom bridge network (not the default bridge), DNS name resolution is native so using the container name is the preferred method to ensure containers can always talk to one another.

If you have AG-Sync and AGH on the same host, simply join the AGH instance to the new bridge network that AG-Sync creates (adguard-sync_default) and the modify your config file to that below:
```
services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run
    environment:
      ORIGIN_URL: http://adguard-adguardhome #172.20.0.2/
      ORIGIN_USERNAME: username
      ORIGIN_PASSWORD: password
      REPLICA_URL: http://10.0.1.3/
      REPLICA_USERNAME: username
      REPLICA_PASSWORD: password
```
![image](https://user-images.githubusercontent.com/1492137/203664672-d27b4366-725f-4340-adca-ac939d28b1a0.png)

Your AGH instance should now be part of two networks; the macvlan and the adguard-sync_default.

**Comment by Daisame** [comment]
Adguard Sync did not make a new netrwork on my docker instance. I tried adding AdGuard Home to my default vlan and see if it could get there through the 172 address and it could not. I am not sure why it cannot get to it over it's own IP (10.100 address space).  
I have AdGuard on it's own VLAN with it's own reserved IP. Different from the external  address of the host PC. I can use all servics normally through this second IP, but for whatever reason. AdGuard Sync does route properly to it. It baffles me.
