### ISSUE TITLE
Different URL for instances on the UI

### ISSUE THREAD

**Issue by tekand** [bakito/adguardhome-sync#258]
### Is your feature request related to a problem? Please describe.

In the config files I use the Docker address of instances. On the UI the links are generated from these. In some cases the public and Docker addresses are not the same.

### Describe the solution you'd like*

One solution would be to have a different attribute for the public URL.

### Describe alternatives you've considered

1. Change IP tables, so that the sync container can access the adguardhome instance via a domain resolved to the host's IP.
2. Move sync container to another Docker host

Neither of them is feasible for me. :(

**Comment by bakito** [comment]
@tekand Thank you for the feature request.

You ask about URL's in the UI.
Do you mean the adguardhome-sync (this application) UI, where you'd like the have an URL override?

**Comment by bakito** [comment]
@tekand can you please provide the requested info?

**Comment by tekand** [comment]
@bakito I apologize, completely forgot about this.
Yes, I meant the adguardhome-sync UI, where on top at the right hand side there are links for the different instances.

Precisely:
https://github.com/bakito/adguardhome-sync/blob/749c5f178ce83027c2dae300073b56a7a20d06f8/pkg/sync/index.html#L60
https://github.com/bakito/adguardhome-sync/blob/749c5f178ce83027c2dae300073b56a7a20d06f8/pkg/sync/index.html#L64

**Comment by bakito** [comment]
@tekand 
I added options to override web urls.
Could you try it out with the newest main image: `docker pull ghcr.io/bakito/adguardhome-sync:main`
https://github.com/bakito/adguardhome-sync/pkgs/container/adguardhome-sync/164378116?tag=main

The web URL settings are documented in the README https://github.com/bakito/adguardhome-sync/commit/4a8e2aab51a740217aba850b6882ab98f2f3e31a#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Comment by tekand** [comment]
Thank you @bakito, it works very well. :)

**Comment by bakito** [comment]
released in https://github.com/bakito/adguardhome-sync/releases/tag/v0.5.4
