### ISSUE TITLE
Proxy for AdGuard Status

### ISSUE THREAD

**Issue by JCapriotti** [bakito/adguardhome-sync#259]
### Is your feature request related to a problem? Please describe.

No problem; I was looking to setup a Heimdall widget that concisely shows the enabled/disabled status of my three AdGuard Home instances. I was thinking if this sync app had an API that returned the status of each configured AdGuard instance it would make configuration of the widget and accessing the statuses much easier.

### Describe the solution you'd like*

The simplest option might be to modify the existing `replicaStatus` type used by the`/api/v1/status` endpoint:

```go
type replicaStatus struct {
	Host   string `json:"origin"`
	URL    string `json:"url"`
	Status string `json:"status"`
	Error  string `json:"error"`
	ProtectionEnabled *bool `json:"protection_enabled"`
}
```

Where ProtectionEnabled is the value returned from the AdGuard Home `/control/status` endpoint. Or, `nil` if the endpoint is unavailable.

I've not used Go, it looked like `*bool` is how to do an optional boolean.

### Describe alternatives you've considered

This feature is more related to AdGuard Home and Heimdall, as opposed to syncing. So the more direct alternative is to just have Heimdall query each AdGuard instance directly. However, the configuration is much messier since a URL, username, and password are required for each instance. 

### Anything else?

I'd be happy to do the update; I wanted to get feedback on this idea before doing that.

**Comment by bakito** [comment]
Hi @JCapriotti 
Thank you for this request.

I can add the flag to the status, the information is already fetched anyway.

Heimdal has already an API integration in adguard-home.
You could also extend this integration, to show the protection status. (Just a thought)

**Comment by JCapriotti** [comment]
Great; I saw the PR... thanks for handling that so fast!

Regarding Heimdall, I was torn between adding to the existing integration vs creating a new one. I'll have to play around with the layout a bit to see if I can make the existing one work for this.

**Comment by bakito** [comment]
The change can be tested in the `latest` image.

**Comment by bakito** [comment]
released with https://github.com/bakito/adguardhome-sync/releases/tag/v0.5.3
