### ISSUE TITLE
How to set Timezone?

### ISSUE THREAD

**Issue by Gamerou** [bakito/adguardhome-sync#264]
### What happened?

First, thank you for this awesome Software!
I know it’s a little thing, but:
I would like to set the correct Timezone, so in the logs it is right.
My Timezone is Europe/Berlin
I tried it with -e TZ=Europe/Berlin in the setup command, but don’t worked.

### AdguardHome-Sync Version

0.5.2

### AdguardHome Version

0.107.43

### Configuration

```shell
Docker cli
Sync between two AdGuard Instances.
```

### Relevant log output

```shell
-
```

**Comment by bakito** [comment]
Hi @Gamerou 

Timezone data was not present in the image, but will be in the next release.

**Comment by bakito** [comment]
released with released with https://github.com/bakito/adguardhome-sync/releases/tag/v0.5.3
