### ISSUE TITLE
Allow configuration of logging encoding

### ISSUE THREAD

**Issue by sapslaj** [bakito/adguardhome-sync#290]
### Is your feature request related to a problem? Please describe.

I use [Loki](https://github.com/grafana/loki) for centralized logs in my homelab. Loki has some nice functions for parsing and querying structured logs. Being able to output logs in logfmt, or more ideally JSON, would be very handy for querying and building alerting rules off of and such.

### Describe the solution you'd like*

Zap already has support for outputting JSON logs, you just have to set the encoding to `"json"` in the `zap.Config`. Either a config option, flag, or environment variable could be used, like `LOG_FORMAT` or similar. Since logging has to be initialized pretty early we could also limit that setting to an environment variable similar to how `LOG_LEVEL` is used currently.

### Anything else?

I'd be happy to submit a PR for this if that makes your life easier.

**Comment by bakito** [comment]
Hi @sapslaj 

This will be part of the next release.

**Comment by bakito** [comment]
Is released with https://github.com/bakito/adguardhome-sync/releases/tag/v0.6.4

**Comment by sapslaj** [comment]
Just updated and it's working like a charm!

![image](https://github.com/bakito/adguardhome-sync/assets/1909600/a910e7b1-b5bd-482c-a941-7da97b6c07fd)
