### ISSUE TITLE
Default config file is $HOME/.adguardhome-sync not $HOME/.adguardhome-sync.yaml

### ISSUE THREAD

**Issue by vrtareg** [bakito/adguardhome-sync#312]
### What happened?

When running `./go/bin/adguardhome-sync run --printConfigOnly` command with correct `$HOME/.adguardhome-sync.yaml` it fails to load the file.

Specifying file explicitly works: `./go/bin/adguardhome-sync run --printConfigOnly --config $HOME/.adguardhome-sync.yaml`

Creating symlink named `$HOME/.adguardhome-sync` pointing to `$HOME/.adguardhome-sync.yaml` resolves the issue.

File `pkg/config/file.go` loads `.adguardhome-sync` instead of `.adguardhome-sync.yaml` in line 35
https://github.com/bakito/adguardhome-sync/blob/0e86fc809435c62d0cabbc0f818ea427f65db696/pkg/config/file.go#L31

### AdguardHome-Sync Version

Latest installed using `go install github.com/bakito/adguardhome-sync@latest`

### AdguardHome Version

`AdGuard Home, version v0.107.45`

### Configuration

```shell
Stand-alone on TrueNAS CORE Jail
```

### Relevant log output

```shell
N/A
```

**Comment by bakito** [comment]
fixed with: #313
