### ISSUE TITLE
SSL for Web UI

### ISSUE THREAD

**Issue by smarthome-enthusiast** [bakito/adguardhome-sync#327]
### Is your feature request related to a problem? Please describe.

I'm trying to have the web UI displayed on HomeAssistant through an iFrame but I'm unable to load HTTP inside a HTTPS web server.

### Describe the solution you'd like*

Would it be possible to support SSL? Maybe through the environment variables on docker file, we could specify the certificate and key and enable SSL on the same port.

### Describe alternatives you've considered

Disabling HTTPS on HomeAssistant but that would make it very insecure during remote access.

**Comment by bakito** [comment]
Hi @smarthome-enthusiast 
Thank you for the feature request.

I can offer you the following:
1. The tls cert files have to be mounted as volume into the Container.
2. The location and names of the certs can be defiend via env variables.
Check https://github.com/bakito/adguardhome-sync/blob/tls-mode/README.md?plain=1#L176 and #329

**Comment by smarthome-enthusiast** [comment]
This would be fantastic.

**Comment by bakito** [comment]
released with: https://github.com/bakito/adguardhome-sync/releases/tag/v0.6.9

**Comment by smarthome-enthusiast** [comment]
Just  updated and it work. Thank you for the quick work and all the work you have done on this!
