### ISSUE TITLE
Is it possible for adguard home sync to read the origin password from AdguardHome.yaml

### ISSUE THREAD

**Issue by rouke-broersma** [bakito/adguardhome-sync#352]
### Is your feature request related to a problem? Please describe.

Currently I need to pass the adguard home password to adguard home sync

### Describe the solution you'd like*

If adguard home sync could be configured to read the password from the adguard home config file, when I run adguard home sync as a sidecar to the origin instance I won't need to set it's password in adguard home sync. It could also read other config like the origin url from the config file.

**Comment by bakito** [comment]
Hi @rouke-broersma 
No Adguardhome-sync can not read Adguardhome config files and is not planned to do so. I uses only Adguardhome API.

Anyway, the config of Adguardhome does not store the password, but only a hash of the password, so it can not be used.
