### ISSUE TITLE
DHCPv4 Options additions are not replicated from Origin to Replica

### ISSUE THREAD

**Issue by stlouey** [bakito/adguardhome-sync#355]
### Is your feature request related to a problem? Please describe.

DHCPv4 options are not replicated.

Origin

dhcpv4: 
   options:
      - 6 ips 10.0.0.20,10.0.0.21

Replica

 dhcpv4:
    options: []

### Describe the solution you'd like*

Origin

dhcpv4: 
   options:
      - 6 ips 10.0.0.20,10.0.0.21

Replica

dhcpv4: 
   options:
      - 6 ips 10.0.0.20,10.0.0.21

### Describe alternatives you've considered

manually add?

### Anything else?

seeking clarification if current solution is supposed to sync or not and if not can it be added?

**Comment by bakito** [comment]
@stlouey Thank you for the request.

Where can you set these options in the web UI?
I can not find any fields for DHCP options.

If it is not available in the web UI and the API, adguardhome-sync can not read/write the values.
