### ISSUE TITLE
RUNONSTART

### ISSUE THREAD

**Issue by techkodeninja** [bakito/adguardhome-sync#356]
### What happened?

  I just setup  adguard-sync and i use the docker-compose with the env, but for some reason it keep saying that the RUNONSTART contains true, which is an invalid type, it should be. a string or number, or a null.

### AdguardHome-Sync Version

latest

### AdguardHome Version

latest

### Configuration

```shell
---
version: "2.1"
services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguardhome-sync
    command: run
    environment:
      LOG_LEVEL: "info"
      ORIGIN_URL: "http://172.16.0.11"
      ORIGIN_USERNAME: "admin"
      ORIGIN_PASSWORD: "#17T793t448nx97wu6i811"

      REPLICA1_URL: "http://172.16.0.36"
      REPLICA1_USERNAME: "admin"
      REPLICA1_PASSWORD: "#17T793t448nx97wu"

      CRON: "0 */2 * * *" # run every 10 minutes
      RUNONSTART: true
      # CONTINUE_ON_ERROR: false # If enabled, the synchronisation task will not fail on single errors, but will log the errors and continue

      # Configure the sync API server, disabled if api port is 0
      API_PORT: 8080
      # API_DARK_MODE: true
      # API_USERNAME: admin
      # API_PASSWORD: secret
      # the directory of the provided tls certs
      # API_TLS_CERT_DIR: /path/to/certs
      # the name of the cert file (default: tls.crt)
      # API_TLS_CERT_NAME: foo.crt
      # the name of the key file (default: tls.key)
      # API_TLS_KEY_NAME: bar.key

      # Configure sync features; by default all features are enabled.
      # FEATURES_GENERAL_SETTINGS: true
      # FEATURES_QUERY_LOG_CONFIG: true
      # FEATURES_STATS_CONFIG: true
      # FEATURES_CLIENT_SETTINGS: true
      # FEATURES_SERVICES: true
      # FEATURES_FILTERS: true
      # FEATURES_DHCP_SERVER_CONFIG: true
      # FEATURES_DHCP_STATIC_LEASES: true
      # FEATURES_DNS_SERVER_CONFIG: true
      # FEATURES_DNS_ACCESS_LISTS: true
      # FEATURES_DNS_REWRITES: true
    ports:
      - 8080:8080
    restart: unless-stopped
```

### Relevant log output

```shell
benlumia007@docker:~/projects/adguard-sync$ docker-compose up -d 
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.adguardhome-sync.environment.RUNONSTART contains true, which is an invalid type, it should be a string, number, or a null
```
```


### Anything else?

_No response_

**Comment by bakito** [comment]
Can you define true as string?

```
RUNONSTART: true
```

**Comment by techkodeninja** [comment]
u mean `RUNONSTART: "true"`

**Comment by techkodeninja** [comment]
also should this be fixed too

```
benlumia007@docker:~/projects/adguard-sync$ docker-compose up -d --force-recreate

Recreating adguardhome-sync ... 

ERROR: for adguardhome-sync  'ContainerConfig'

ERROR: for adguardhome-sync  'ContainerConfig'
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 33, in <module>
    sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
    handler(command, command_options)
  File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
    result = fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up
    to_attach = up(False)
  File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up
    return self.project.up(
  File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up
    results, errors = parallel.parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do
    return service.execute_convergence_plan(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 579, in execute_convergence_plan
    return self._execute_convergence_recreate(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 499, in _execute_convergence_recreate
    containers, errors = parallel_execute(
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
    raise error_to_reraise
  File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
    result = func(obj)
  File "/usr/lib/python3/dist-packages/compose/service.py", line 494, in recreate
    return self.recreate_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 612, in recreate_container
    new_container = self.create_container(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container
    container_options = self._get_container_create_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 921, in _get_container_create_options
    container_options, override_options = self._build_container_volume_options(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 960, in _build_container_volume_options
    binds, affinity = merge_volume_bindings(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1548, in merge_volume_bindings
    old_volumes, old_mounts = get_container_data_volumes(
  File "/usr/lib/python3/dist-packages/compose/service.py", line 1579, in get_container_data_volumes
    container.image_config['ContainerConfig'].get('Volumes') or {}
KeyError: 'ContainerConfig'
```
i can't force recreate the container...

**Comment by bakito** [comment]
> also should this be fixed too
> 
> ```
> benlumia007@docker:~/projects/adguard-sync$ docker-compose up -d --force-recreate
> 
> Recreating adguardhome-sync ... 
> 
> ERROR: for adguardhome-sync  'ContainerConfig'
> 
> ERROR: for adguardhome-sync  'ContainerConfig'
> Traceback (most recent call last):
>   File "/usr/bin/docker-compose", line 33, in <module>
>     sys.exit(load_entry_point('docker-compose==1.29.2', 'console_scripts', 'docker-compose')())
>   File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 81, in main
>     command_func()
>   File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 203, in perform_command
>     handler(command, command_options)
>   File "/usr/lib/python3/dist-packages/compose/metrics/decorator.py", line 18, in wrapper
>     result = fn(*args, **kwargs)
>   File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1186, in up
>     to_attach = up(False)
>   File "/usr/lib/python3/dist-packages/compose/cli/main.py", line 1166, in up
>     return self.project.up(
>   File "/usr/lib/python3/dist-packages/compose/project.py", line 697, in up
>     results, errors = parallel.parallel_execute(
>   File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
>     raise error_to_reraise
>   File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
>     result = func(obj)
>   File "/usr/lib/python3/dist-packages/compose/project.py", line 679, in do
>     return service.execute_convergence_plan(
>   File "/usr/lib/python3/dist-packages/compose/service.py", line 579, in execute_convergence_plan
>     return self._execute_convergence_recreate(
>   File "/usr/lib/python3/dist-packages/compose/service.py", line 499, in _execute_convergence_recreate
>     containers, errors = parallel_execute(
>   File "/usr/lib/python3/dist-packages/compose/parallel.py", line 108, in parallel_execute
>     raise error_to_reraise
>   File "/usr/lib/python3/dist-packages/compose/parallel.py", line 206, in producer
>     result = func(obj)
>   File "/usr/lib/python3/dist-packages/compose/service.py", line 494, in recreate
>     return self.recreate_container(
>   File "/usr/lib/python3/dist-packages/compose/service.py", line 612, in recreate_container
>     new_container = self.create_container(
>   File "/usr/lib/python3/dist-packages/compose/service.py", line 330, in create_container
>     container_options = self._get_container_create_options(
>   File "/usr/lib/python3/dist-packages/compose/service.py", line 921, in _get_container_create_options
>     container_options, override_options = self._build_container_volume_options(
>   File "/usr/lib/python3/dist-packages/compose/service.py", line 960, in _build_container_volume_options
>     binds, affinity = merge_volume_bindings(
>   File "/usr/lib/python3/dist-packages/compose/service.py", line 1548, in merge_volume_bindings
>     old_volumes, old_mounts = get_container_data_volumes(
>   File "/usr/lib/python3/dist-packages/compose/service.py", line 1579, in get_container_data_volumes
>     container.image_config['ContainerConfig'].get('Volumes') or {}
> KeyError: 'ContainerConfig'
> ```
> 
> i can't force recreate the container...

This is a docker compose issue and not an issue of adguardhome-sync

**Comment by techkodeninja** [comment]
got it. i kinda figure it was the docker-compose issue. thanks for verifying.
