### ISSUE TITLE
Trigger a sync via API

### ISSUE THREAD

**Issue by bazza888** [bakito/adguardhome-sync#361]
### Is your feature request related to a problem? Please describe.

No problem just a request

### Describe the solution you'd like*

I'd like to see a basic API to trigger an on demand sync

### Describe alternatives you've considered

Considered opening the website via script and using a click method via web element.

**Comment by bakito** [comment]
This is possible with POST `/api/v1/sync`

**Comment by bazza888** [comment]
Absolute legend thank you
Sorry I was not able to find it within the GitHub repository. Perhaps a small addition to the README ? :)
Thank you very much
