### ISSUE TITLE
Container error code 139 then restarts

### ISSUE THREAD

**Issue by Martin-Dolan** [bakito/adguardhome-sync#372]
### What happened?

Installed many times, many different ways, it seems that the container does not even start properly as there is nothing in the logs.
I am running on Pi-os  , latest boobworm version with all the updates on raspberry pi 5

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian

Tried deploying by command line with docker,  and by using portainer..  same thing.   just exits with error 139 , no output.

I also made a new container with portainer using the hello-world example, that worked, had something in the log files, so I know the system works enough to deploy a container..
also adguardhome is running fine on this system in another container

### AdguardHome-Sync Version

v 0.6.11 
(fresh off site as of 23/07/24)

### AdguardHome Version

Version:   v0.107.51 
but its not even getting that far to even try and connect.

### Configuration

```shell
tried lots of different configs, but even just this basic one should get it to run and output an error, but not even that happens. (trying to keep it as basic as possible to get it to at least start...
---------
version: "2.1"
services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync
    container_name: adguard_syncTest3
    command: run
    ports:
      - 8084:8080
    restart: unless-stopped
```

### Current Applied Configuration

```shell
tried that, no output what so ever
```

### Relevant log output

```shell
Doesn't show anything in logs
```

### Anything else?

I wish I had a log file to paste here..  then i'd have something to work with..
Thinking the code just does not run on this version of raspberry pi OS

`cat /etc/os-release `
gives:
`PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"`

**Comment by bakito** [comment]
Hi @Martin-Dolan 
Are you running the binary or docker version?
Can you please provide the cpu arch of your pi?

`uname -m`

**Comment by Martin-Dolan** [comment]
The raspberry pi 5 is a 64-bit 2.4 GHz quad-core ARM Cortex-A76
I know people have successfully run it on raspberry pi 3 (different chip though)

I'm running the docker version.   
I've tried installing it using both methods using Docker CLI and docker compose  - (ghcr.io/bakito/adguardhome-sync)

**Comment by bakito** [comment]
what us the output of  `uname -m`

**Comment by Martin-Dolan** [comment]
aarch64

**Comment by Martin-Dolan** [comment]
Ahh ok..  That makes sense.
It's the first time I've tried to set this up, and also the first time I've used docker, portainer and a pi 5 so I want sure if it was because it didn't work /wasn't supported or because I was doing something wrong /stupid/uneducated 🤣
That's why gave it a good go before bothering you! 
Also learnt a hell of a lot over the last week and a bit..

Let me know when you want me to test it!

**Comment by bakito** [comment]
@Martin-Dolan can you please try the most recent `main` tag image?

https://github.com/bakito/adguardhome-sync/pkgs/container/adguardhome-sync

**Comment by Martin-Dolan** [comment]
Still nothing :(
I used `ghcr.io/bakito/adguardhome-sync:main`

`version: "2.1"
services:
  adguardhome-sync:
    image: ghcr.io/bakito/adguardhome-sync:main
    container_name: adguardhome-sync
    command: run --config /config/adguardhome-sync.yaml
    volumes:
      - /DATA/AppData/adguardhome-sync/config/adguardhome-sync.yaml:/config/adguardhome-sync.yaml`

Also tried the same with `ghcr.io/bakito/adguardhome-sync:alpine-main`

so is it downloading the right version for my system?  

Let me know if I'm doing something stupid...

**Comment by bakito** [comment]
Actially I`m a bit puzzled on which arch is really needed, as I can not test it myself.

Can you give this image a try? 
`quay.io/bakito/adguardhome-sync`

Do you have other docker images/applications that run?

If so, can you run `docker inspect <image-name>`

And do the same with adguardhome sync?

`docker inspect ghcr.io/bakito/adguardhome-sync:main`

And attach the output?

I'm specially intrested in the Architecture an OS sections.

**Comment by Martin-Dolan** [comment]
No problem, I'll do it as soon as I get home.

You know more about this than I do, but as far as I can work out from what I've read, the pi 5 uses arm64  aarch64

This might help? 

https://www.raspberrypi.com/documentation/computers/linux_kernel.html

Also if I open a shell from casa os I get :

Linux raspberrypi 6.6.31+rpt-rpi-2712 #1 SMP PREEMPT Debian 1:6.6.31-1+rpt1 (2024-05-2 9) aarch64

**Comment by Martin-Dolan** [comment]
Holly sh!t  I think you fixed it.
I just ran the docker hello world example again and that said arm64v8   

I then noticed you put some more arch versions up and one was arm64v8, so I downloaded adguardhome-sync again and it actually ran this time - well it has something in the log files at least which is a start!  ill go and test it actually works now, but at least its running!!  
thank you sooooooo much!!!!

**Comment by bakito** [comment]
Good to hear, I'll close the isseu then.

**Comment by Martin-Dolan** [comment]
Yes, just been testing- It's just various config/settings stuff I have to work out now, but it did the symc of 5 pages of static leases which is good! 
Thanks again <3

**Comment by bakito** [comment]
a new release is currently being built
