### ISSUE TITLE
Modify the way that DHCP settings are synced

### ISSUE THREAD

**Issue by danps1** [bakito/adguardhome-sync#38]
**Is your feature request related to a problem? Please describe.**
I have 2 servers with adguardhome-sync copying settings between, and have noticed some errors in how I think replication of DHCP settings should take place. My 2 servers have different network settings (different NIC names / VLANS)
It appears that adgaurdhome-sync is attempting to sync all DHCP settings. I think it would be preferable to sync just some

**Describe the solution you'd like**
With 2 DHCP Servers on the same subnet standard practice would be to configure each with a seperate non-overlapping range of addresses within the same CIDR range. This is to prevent IP address conflicts caused by the 2 servers handing the same address to 2 different clients.
Suggestion would be not to sync the DHCP range setting.
Also with difference between servers possible in terms of network name etc, suggesting would be to also not sync this setting.
The setting that I think would be good to sync, but doesn't seem to be in my setup is the DHCP Static Reservations - the benefit here is that both servers should have the same static reservations to server these clients correctly

**Describe alternatives you've considered**
No alternatives that I can think of

**Additional context**

**Comment by bakito** [comment]
Hi 

Thank you fro you request.
Actually I was asking something similar when DHCP sync was requested in https://github.com/bakito/adguardhome-sync/issues/12#issuecomment-829869581

I'm thinking of some kind of feature flags, but not sure yet on how to implement it.

Let me think about it.

**Comment by danps1** [comment]
Yeah I agree, maybe some kind of option in the config file to choose what to sync? Thanks

**Comment by bakito** [comment]
Hi @danps1 

Sorry, it took me a while.

I added a skip DHCp flag.

Can you please check if this fits your requirements, by using the main build image: 
`docker pull ghcr.io/bakito/adguardhome-sync:main`


The flag can be set by setting the env variable
`- SKIP_DHCP=false`
or config param:

```
skip:
  # skip DCP sync
  dhcp: false
```

**Comment by bakito** [comment]
Thank you very much for the feedback.
I used skip, since the sync was previousely enabled by default. Hence skip, to keep the default behaviour.

I'll check if the config could be applied just with the static reservations. Not sure if it wotks, since it's all in one request. It dependts on how it is implemented on adguard home side.

**Comment by bakito** [comment]
Hi @danps1 

After checking the backend implementation, the current code and your proposal, I tried another approach.
I removed the skip part and introduced a features config, where all features are disabled by default (currently only dhcp)

```
features:
  dhcp:
    serverConfig: false
    staticLeases: true
```

env:
```

 - FEATURES_DHCP_SERVERCONFIG=false
 - FEATURES_DHCP_STATICLEASES=false
```

**Comment by danps1** [comment]
Thanks @bakito,
This is what I see with both env variables false...
```
      - FEATURES_DHCP_SERVER_CONFIG=false
      - FEATURES_DHCP_STATIC_LEASES=false
```
```
2021-11-01T23:20:47.790Z	INFO	root	cmd/root.go:114	Using config file:/config/adguardhome-sync.yaml
2021-11-01T23:20:47.792Z	INFO	sync	sync/sync.go:30	AdGuardHome sync	{"version": "main", "build": "2021-11-01T17:38:51Z"}
2021-11-01T23:20:47.792Z	INFO	sync	types/features.go:45	Disabled features	{"features": "[DHCP.ServerConfig,DHCP.StaticLeases]"}
```
And with Static Lease sync enabled...
```
      - FEATURES_DHCP_SERVER_CONFIG=false
      - FEATURES_DHCP_STATIC_LEASES=true
```
```
2021-11-01T23:25:25.991Z	INFO	root	cmd/root.go:114	Using config file:/config/adguardhome-sync.yaml
2021-11-01T23:25:25.992Z	INFO	sync	sync/sync.go:30	AdGuardHome sync	{"version": "main", "build": "2021-11-01T17:38:51Z"}
2021-11-01T23:25:25.993Z	INFO	sync	types/features.go:45	Disabled features	{"features": "[DHCP.ServerConfig,DHCP.StaticLeases]"}
```
It seems to still be disabled?
I also tried by setting the same values in config file, and the same thing - both config and leases seem disabled regardless.
Thanks
Dan

**Comment by bakito** [comment]
Hi Dan

There seems to be an issue in how the flags are parsed. I had to change the feature flags to 
```
      - FEATURES_DHCP_SERVERCONFIG=false
      - FEATURES_DHCP_STATICLEASES=true

```
A new main image is currently being built.

**Comment by bakito** [comment]
included in https://github.com/bakito/adguardhome-sync/releases/tag/v0.3.2

**Comment by danps1** [comment]
Hi @bakito,

Apologies, life got in the way and I only just got round to testing this. Works perfectly now. 

Thanks very much!
