### ISSUE TITLE
feature request: docker image 

### ISSUE THREAD

**Issue by elRadix** [bakito/adguardhome-sync#4]
as all my apps are running as Docker apps,. would be great if you can create a Docker app

**Comment by JoshStark** [comment]
There is currently an image LinuxServer.io is testing which can be used: https://github.com/TheSpad/docker-adguardhome-sync
Hopefully this is something we will get into the main repository soon.

**Comment by lg0killer** [comment]
The docker image is building and running on my system.

Just note I created the config file and then just mapped it from disk to container using -v <path on disk>:/config/adguardhome-sync.yaml

**Comment by bakito** [comment]
I added a docker image that is hosted on quay.io.

See the instructions in the readme.

**Comment by elRadix** [comment]
works great, I like the very small image 3.5mb!!
