### ISSUE TITLE
Option to not change the theme

### ISSUE THREAD

**Issue by truncsphere** [bakito/adguardhome-sync#403]
### Is your feature request related to a problem? Please describe.

With 2 instances, I keep one theme on dark and the other on the light theme to easily differentiate which one I'm looking at. 

### Describe the solution you'd like*

I would like an option to not sync the theme between the 2 devices. 

### Describe alternatives you've considered

I tried disabling the General sync, but that does not include the theme.

**Comment by bakito** [comment]
The next release will have a feature flag: FEATURES_THEME the if set to false disabled the theme sync

**Comment by bakito** [comment]
Released in v0.6.13

**Comment by truncsphere** [comment]
> Released in v0.6.13

Just tested and confirmed working. Thank you for the quick implementation!
