### ISSUE TITLE
Error Getting Origin Status

### ISSUE THREAD

**Issue by paterson37** [bakito/adguardhome-sync#410]
### What happened?

I'm going to preface this by saying I'm quite the novice when it comes to Linux and/or Home Assistant.

I'm running my origin AGH instance via Home Assistant on a Raspberry Pi and got my replica on a separate linux pc.

I've set up Adguard Home Sync via the Run As Linux Service method. I've updated the yaml with the information I assume I need to input.

However when it tries to sync I get the below error when SSL is enabled on the AdGuard Home add-on on Home Asssistant.

` 2024-09-22T19:02:15.218+0100	ERROR	sync	sync/sync.go:165	 Error getting origin status	{"from": "192.168.X.X:85", "error": ": Get \"https://192.168.X.X:85/control/status\": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.X.X because it doesn't contain any IP SANs"}`

I've tried disabled the SSL on the Home Assistant Add One but I then get the below error which is different to the above.

`2024-09-22T18:59:25.698+0100	ERROR	sync	sync/sync.go:165	Error getting origin status	{"from": "192.168.X.X:85", "error": ": Get \"https://192.168.X.X:85/control/status\": http: server gave HTTP response to HTTPS client"}`

### AdguardHome-Sync Version

0.6.12

### AdguardHome Version

 v0.107.52

### Configuration

```shell
# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "0 */1 * * *"

# runs the synchronisation on startup
runOnStart: true

# If enabled, the synchronisation task will not fail on single errors, but will log the errors and continue
continueOnError: false

origin:
  # url of the origin instance
  url: https://192.168.X.X:85
  # apiPath: define an api path if other than "/control"
  # insecureSkipVerify: true # disable tls check
  username: REDACTED
  password: REDACTED
  # cookie: Origin-Cookie-Name=CCCOOOKKKIIIEEE

# replicas instances
replicas:
  # url of the replica instance
  - url: http://192.168.X.X:85
    username: REDACTED
    password: REDACTED
    # cookie: Replica1-Cookie-Name=CCCOOOKKKIIIEEE
    # autoSetup: true # if true, AdGuardHome is automatically initialized.
    # webURL: "https://some-other.url" # used in the web interface (default: <replica-url>

# Configure the sync API server, disabled if api port is 0
api:
  # Port, default 8080
  port: 8080
  # if username and password are defined, basic auth is applied to the sync API
  username: REDACTED
  password: REDACTED
  # enable api dark mode
  darkMode: true

    # enable metrics on path '/metrics' (api port must be != 0)
    # metrics:
    # enabled: true
  # scrapeInterval: 30s 
  # queryLogLimit: 10000

  # enable tls for the api server
  # tls:
  #   # the directory of the provided tls certs
  #   certDir: /path/to/certs
  #   # the name of the cert file (default: tls.crt)
  #   certName: foo.crt
  #   # the name of the key file (default: tls.key)
  #   keyName: bar.key

# Configure sync features; by default all features are enabled.
features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: true
    staticLeases: true
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true
```

### Relevant log output

```shell
2024-09-22T19:02:15.218+0100	ERROR	sync	sync/sync.go:165	 Error getting origin status	{"from": "192.168.X.X:85", "error": ": Get \"https://192.168.X.X:85/control/status\": tls: failed to verify certificate: x509: cannot validate certificate for 192.168.X.X because it doesn't contain any IP SANs"}



-------------------------------------------------------------

2024-09-22T18:59:25.698+0100	ERROR	sync	sync/sync.go:165	Error getting origin status	{"from": "192.168.X.X:85", "error": ": Get \"https://192.168.X.X:85/control/status\": http: server gave HTTP response to HTTPS client"}
```

**Comment by bakito** [comment]
Hi
When you disable ssl, you need to change the url in the config from https to http.

When connecting via https you need to use the url of your home assistant, as it seems the ssl certificate is not valid for the IP. If that is not possible, you could try `insecureSkipVerify: true` in the origin config

**Comment by paterson37** [comment]
Thanks very much. That seems to have made progress.

Unfortunately I'm getting the below error now.

`2024-09-22T19:35:25.723+0100	ERROR	sync	sync/sync.go:296	Error syncing actionFilters	{"from": "192.168.X.X:85", "to": "192.168.X.X:85", "error": "400 Bad Request(Couldn't fetch filter from URL \"https://raw.githubusercontent.com/hagezi/dns-blocklists/main/whitelist.txt\": reading from url: got status code 404, want 200\n)"}`

Is this something on my end or something to do with the filter list I use?

**Comment by bakito** [comment]
This filter is configured in your origin instance and the url does not exits.
Remove the url in your origin

**Comment by Permanently** [comment]
@bakito what's the .env equivalent for `insecureSkipVerify`? This isn't documented anywhere.

**Comment by bakito** [comment]
> [@bakito](https://github.com/bakito) what's the .env equivalent for `insecureSkipVerify`? This isn't documented anywhere.

E.g: ORIGIN_INSECURE_SKIP_VERIFY
