### ISSUE TITLE
Error getting origin status (404)

### ISSUE THREAD

**Issue by RavHilton** [bakito/adguardhome-sync#43]
**Describe the bug**
When I set up AdGuard Home in 2 separate Docker environments and then configured AdGuardHome-Sync on the primary instance, it synched as expected.  Now, a couple of days later, it fails with a 404 error even though both AdGuard Home instances are online, and have not been changed.

**To Reproduce**
1. What version of AdGuardHome sync used? "version": "v0.3.2", "build": "2021-11-10T18:32:32Z"
2. What version of AdGuardHome us used? Version: v0.106.3 on both instances.
3. How does the configuration look? Unchanged
4. What is the error message? ERROR	sync	sync/sync.go:99	Error getting origin status	{"from": "10.1.2.3", "error": "404 Not Found"}

**Expected behavior**
I would expect synching to work as it did initially..

**Screenshots**
If applicable, add log files or json responses from AdGuardHome to help explain your problem.
- Happy to provide if needed.

**Additional context**
- Nope, just that I've restarted all services involved and no change.  And both AdGuard Home instances are online and working.

**Comment by bakito** [comment]
Hi @RavHilton 
Hard to guess the issue with that few information.
It sounds as if the second instance was either not running or initialized.

**Comment by RavHilton** [comment]
As I said, it was running before and worked.  Nothing has changed (same versions, both the primary and secondary instances of AdGuard Home are running and resolving, same versions as a week ago when AdGuardHome-Sync was working).

Interesting that you suggest that the secondary may not be working when the issue is regarding the primary instance that it cannot connect (yet I can get to the web interface and can resolve through both the primary and secondary).

If you want more information, what would you like?  As I said, happy to give more info, but if you don't ask for what you need, that doesn't help.

**Comment by RavHilton** [comment]
2021-12-07T03:40:00.099Z	ERROR	sync	sync/sync.go:99	Error getting origin status	{"from": "10.1.2.3:3000", "error": "Get \"https://10.1.2.3:3000/control/status\": EOF"}
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
	/go/src/app/pkg/sync/sync.go:99
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func2
	/go/src/app/pkg/sync/sync.go:44
github.com/robfig/cron/v3.FuncJob.Run
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136
github.com/robfig/cron/v3.(*Cron).startJob.func1
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312

I've tried using the web interface port for the primary (the web interface is on 3080, and 3000 is also open) as well, with a similar failed attempt to sync from it.

**Comment by bakito** [comment]
How does your configuration look.

'unchanged' does not say much about your setup.

What port do you use in the config. - this has to be the same as you connect to the web UI.

You can change the log level of adguardhome-sync by setting the environment variable **LOG_LEVEL=debug** in your instance.

Do you see any errors in the adguardhome instance that is not reachable?

Do you get a result for that URL https://10.1.2.3:3000/control/status when you enter it in the browser? -> you need do log in first in the web UI

**Comment by RavHilton** [comment]
I blew AdGuardHome-Sync away, redid from scratch, and it s now syncing (as the last one did initially).  Will see how it goes in a week or so.
