### ISSUE TITLE
Does not sync the setting "allow_unencrypted_doh: true" from the TLS section

### ISSUE THREAD

**Issue by iluvatyr** [bakito/adguardhome-sync#450]
### What happened?

I wanted to sync two adguard instances. It works great.

One thing that did not sync (maybe intentionally?) is the option:
` allow_unencrypted_doh: true`
within the TLS Section.
 
 Since I use DoH behind a reverseproxy  (which holds the certificates) and then transmit the dns requests via wireguard (tailscale) to the adguard instance, I just set it up without TLS certificates and therefore needed the option:

 "allow_unencrypted_doh: true
 
 This setting did not sync by itself. Would be nice if there could be an option to sync this setting aswell.

### AdguardHome-Sync Version

0.6.13 (2024-09-28T07:06:27Z)

### AdguardHome Version

"v0.107.54"}

### OS Information

All systems where running as docker containers under ubuntu 22.04

### Configuration

```shell
# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "*/10 * * * *"

origin:
  # url of the origin instance
  url: http://IP:80
  # apiPath: define an api path if other than "/control"
  insecureSkipVerify: true # disable tls check
  username: user
  password: PW

# replica instance (optional, if only one)
replica:
  # url of the replica instance
  url: http://IP1:80
  insecureSkipVerify: true
  username: user
  password: PW


# Configure the sync API server, disabled if api port is 0
api:
  # Port, default 8080
  port: 8081
  # if username and password are defined, basic auth is applied to the sync API
  username: user
  password: PW
```

### Current Applied Configuration

```shell
-
```

### Relevant log output

```shell
-
```

**Comment by bakito** [comment]
Hi @iluvatyr 

Where is this parameter set in the web UI?

adguardhome-sync can only sync parameter that are exposed by the API of adguardhome. 
If the parameter is only defined in the AdGuardHome.yaml and not in the API, then it can not be synched.

**Comment by iluvatyr** [comment]
oh okay ,then this is why. It is only within the adguardhome.yaml.
