### ISSUE TITLE
Option to sync the Query Log between two instances?

### ISSUE THREAD

**Issue by GRRemlin** [bakito/adguardhome-sync#458]
### Is your feature request related to a problem? Please describe.

I saw the Metric section in the config file and enabled it, assuming it would sync the query log.

  _# enable metrics on path '/metrics' (api port must be != 0)_
  _metrics:_
  _enabled: true_
  _scrapeInterval: 30s_ 
  _queryLogLimit: 10000_

So far I am not seeing anything regarding the metrics in the API log or on the replica.

### Describe the solution you'd like*

Would it be possible to implement query log sync so I could monitor them from one instance?

Thanks in advance!

**Comment by bakito** [comment]
Hi @GRRemlin 
No this is not possible.
The only way to get the info of the combined logs is via the enabled metrics on adguard-home sync.
If enabled, you get the metrics in prometheus syntax on its /metrics endpoint.
Form there one can process it e.g. with prometheus and visualize it with grafana.

**Comment by GRRemlin** [comment]
Understood. Thank you very much for a quick reply!

**Comment by bakito** [comment]
@GRRemlin In v0.6.14 I added a feater in the agduardhome-sync UI to show consolidates stats diagrams. #459

API and metrics need to be enabled for this:
```
api:
  port: 8080
  metrics:
    enabled: true
```

**Comment by GRRemlin** [comment]
That is awesome, thank you so much!

I'm still having trouble accessing the endpoint though. It must be my lack of knowledge.
I'm running it in Portainer and can access the API page via port 8080, see the sync logs etc just fine.
But when trying to access the http://ip_address:8080/metrics endpoint, I get 404

_api:
  port: 8080
  username: 
  password: 
  darkMode: true
  metrics:
    enabled: true
  scrapeInterval: 30s 
  queryLogLimit: 10000_

**Comment by bakito** [comment]
Please check the indents of your config file.
The above config does not show any indents (spaces)
Can you post your config formatted as code.

**Comment by GRRemlin** [comment]
Yes, my apologies:

```
api:
  port: 8080
  username: 
  password: 
  darkMode: true
  metrics:
    enabled: true
  scrapeInterval: 30s 
  queryLogLimit: 10000
```

**Comment by bakito** [comment]
This seems correct.
Try printing the config. https://github.com/bakito/adguardhome-sync/wiki/FAQ#how-to-print-the-current-applied-configuration

And check if this current config of the app is correct.

**Comment by GRRemlin** [comment]
The config was correct and after re-creating the container again the graphs show up!
Thank you again for being patient with me and very helpful!
