### ISSUE TITLE
Cannot see log, there is a black overlay

### ISSUE THREAD

**Issue by iptvcld** [bakito/adguardhome-sync#468]
### What happened?

Cannot see log, there is a black overlay

![image](https://github.com/user-attachments/assets/f5666831-dca6-43fb-86c7-33b661fcaa5b)

### AdguardHome-Sync Version

0.6.15

### AdguardHome Version

Version: 
v0.107.55

### OS Information

Unraid Docker

### Configuration

```shell
Unraid Docker
```

### Relevant log output

```shell
Cannot see log, there is a black overlay
```

### Anything else?

See screenshot

**Comment by bakito** [comment]
fixed in: https://github.com/bakito/adguardhome-sync/releases/tag/v0.6.16 ([Images must be built first](https://github.com/bakito/adguardhome-sync/actions/runs/12388414784))

**Comment by iptvcld** [comment]
thank you, it works now!
