### ISSUE TITLE
2-way sync

### ISSUE THREAD

**Issue by tam481** [bakito/adguardhome-sync#477]
### Is your feature request related to a problem? Please describe.

It would be great to be able to sync differences between two instances. I am relatively new to adguardhome-sync and already I messed up by updating my replica instead of the primary instance and then synchronised only to have the settings overwritten.

It was a silly mistake but it made me wonder whether you had plans to create the ability to do two-way synchronisation between two instances of Adguardhome

### Describe the solution you'd like*

Ability to synchronise in both directions between two instances of Adguard Home

### Describe alternatives you've considered

n/a

### Anything else?

Thank you very much indeed in advance for this great software even if you have no plans to implement this feature.

**Comment by jack-samo10000** [comment]
Hello, we tried to solve the issue.

This is what we did:

Add functionality to allow two-way synchronization between AdGuard Home instances. This includes modifying the config structure, sync logic, and adding new API endpoints.

You can review changes in this commit: https://github.com/jack-samo10000/bakito-adguardhome-sync-477/commit/d843f9f62a44f121ec61519efb53aed07bc36aa3.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by tam481** [comment]
Oh wow. That's great to hear. I can't review the commit as I have virtually no coding skills so I wouldn't know what I'm looking at :-)

Do you have any plans to merge this into the main branch soon?

p.s. I'm a bit confused about the AI disclaimer. Are you saying you used AI to create the necessary code to enable two-way synchronisation? I guess you're the expert but in my experience playing with AI to create a bit of code didn't work. It simply made up some commands that did not exist as functions.

**Comment by bakito** [comment]
> Oh wow. That's great to hear. I can't review the commit as I have virtually no coding skills so I wouldn't know what I'm looking at :-)
> 
> Do you have any plans to merge this into the main branch soon?
> 
> p.s. I'm a bit confused about the AI disclaimer. Are you saying you used AI to create the necessary code to enable two-way synchronisation? I guess you're the expert but in my experience playing with AI to create a bit of code didn't work. It simply made up some commands that did not exist as functions.

I guess this comment is not ment to be in this issue

**Comment by bakito** [comment]
@tam481 This is not planned and to conplex.
Imagine having 3 or more instances that are all synched with each other. 🫣

To separate origin and replica you can set one instance to dark theme and the other to light and disable the theme sync feature.
See https://github.com/bakito/adguardhome-sync/issues/403#issuecomment-2366927979
