### ISSUE TITLE
New log duration (6hrs) breaks sync if selected

### ISSUE THREAD

**Issue by gf78** [bakito/adguardhome-sync#49]
**Describe the bug**
At least from AdGuard version 0.107.2 on the storage duration for logs can be set to 6hrs (0.25 days). If 6hrs are selected - even if logging is disabled at all - the sync fails with the following error:

`ERROR	sync	sync/sync.go:143	Error getting query log config	{"from": "x.x.x.x:xxxx", "error": "json: cannot unmarshal number 0.25 into Go struct field QueryLogConfig.interval of type int"}`

**To Reproduce**
1. What version of AdGuardHome sync used? quay.io/bakito/adguardhome-sync, ID c3dbf3ea71c8
2. What version of AdGuardHome us used? 0.107.2
3. How does the configuration look? 6hrs logging period
4. What is the error message? see above

**Expected behavior**
Support the new setting, change the used data format from int to float.

**Log Files**
see above

**Additional context**
none

**Comment by bakito** [comment]
Thank you for reporting this issue.

It is fixed in vesion https://github.com/bakito/adguardhome-sync/releases/tag/v0.4.0

Please be aware, that origin and replicas must have AdGuard Home >= v0.107.0
