### ISSUE TITLE
Can't sync. Strange message about auto redirect is disabled

### ISSUE THREAD

**Issue by PeterVoronov** [bakito/adguardhome-sync#59]
**Describe the bug**
I have a two servers in docker behind traefik. Found via google search your amazing product.
Now trying to use - and faced with problem - I can't sync my two servers.
Most interesting thing - i tried to change the order of syncing - I had the same error

**To Reproduce**
1. What version of AdGuardHome sync used? 0.4.2, in container by linuxserver.
2. What version of AdGuardHome us used? v0.107.3
3. How does the configuration look?
```#cron: "*/10 * * * *"

runOnStart: true

origin:
  # url of the origin instance
  url: https://adguard-cat.my.org
  # apiPath: define an api path if other than "/control"
  # insecureSkipVerify: true # disable tls check
  username: admin
  password: *

# replica instance (optional, if only one)
replica:
  # url of the replica instance
  url: http://adguard-two.my.org
  username: admin
  password: *

# replicas instances (optional, if more than one)
replicas:

# Configure the sync API server, disabled if api port is 0
api:
  # Port, default 8080
  port: 8080
  # if username and password are defined, basic auth is applied to the sync API.
  #username:.
  #password:.

features:
  generalSettings: false
  queryLogConfig: false
  statsConfig: false
  clientSettings: false
  services: false
  filters: false
  dhcp:
    serverConfig: false
    staticLeases: false
  dns:
    serverConfig: true
    accessLists: false
    rewrites: false
```
4. What is the error message?
```Error getting replica status	{"from": "adguard-two.my.org", "to": "adguard-one.my.org", "error": "Get \"https://adguard-one.catshome.name/control/status\": auto redirect is disabled"}```
But, when I set reverse order of sync, i.e. origin.url = http://adguard-two.my.org and replica.url=https://adguard-cat.my.org
I had error with adguard-cat.my.org!
```Error getting replica status    {"from": "adguard-two.catshome.name", "to": "adguard-cat.catshome.name", "error": "Get \"https://adguard-cat.catshome.name/control/status\": auto redirect is disabled"}```
Most interesting things:
- sync from two to cat:
  -  2022-02-03T18:43:05.668+0200    DEBUG   **client  client/client.go:114    do get**  {"host": "**adguard-cat.my.org**", "method": "GET", "path": "status", "username": "admin"}
2022-02-03T18:43:05.748+0200    DEBUG   client  client/client.go:126    **got response**    {"host": "**adguard-cat.my.org**", "method": "GET", "path": "status", "username": "admin", **"status": 200**, "body": "{\"dns_addresses\":[\"127.0.0.1\",\"172.23.0.11\"],\"dns_port\":53,\"http_port\":80,\"protection_enabled\":true,\"dhcp_available\":true,\"running\":true,\"version\":\"v0.107.3\",\"language\":\"\"}\n"}
  -  2022-02-03T18:43:06.435+0200    DEBUG   **client  client/client.go:114    do get**  {"host": "**adguard-two.my.org**", "method": "GET", "path": "status", "username": "admin"}
2022-02-03T18:43:06.441+0200    DEBUG   client  client/client.go:123    **error in do get** {"host": "**adguard-two.my.org**", "method": "GET", "path": "status", "username": "admin", **"status": 301**, "body": "", "error": "Get \"https://adguard-two.my.org/control/status\": auto redirect is disabled"}
- sync cat to two:
  - 2022-02-03T18:37:35.773+0200    DEBUG   **client  client/client.go:114    do get**  {"host": "**adguard-two.my.org**", "method": "GET", "path": "status", "username": "admin"}
2022-02-03T18:37:35.958+0200    DEBUG   client  client/client.go:126    **got response**    {"host": "adguard-two.my.org", "method": "GET", "path": "status", "username": "admin", **"status": 200**, "body": "{\"dns_addresses\":[\"127.0.0.1\",\"172.23.0.9\"],\"dns_port\":53,\"http_port\":80,\"protection_enabled\":true,\"dhcp_available\":true,\"running\":true,\"version\":\"v0.107.3\",\"language\":\"\"}\n"}
  - 2022-02-03T18:37:36.962+0200    DEBUG   **client  client/client.go:114    do get**  {"host": "**adguard-cat.my.org**", "method": "GET", "path": "status", "username": "admin"}
2022-02-03T18:37:36.966+0200    DEBUG   client  client/client.go:123    **error in do get** {"host": "adguard-cat.my.org", "method": "GET", "path": "status", "username": "admin", **"status": 301**, "body": "", "error": "Get \"https://adguard-cat.my.org/control/status\": auto redirect is disabled"}
So, in case of primary source - everything is ok. But with replica - "redirect detected" ... With the same servers and urls!
I have no idea, except the something not cleared in the transport (i.e. get ...) and it identified changing the dns name as redirect ...
As additional proof - please look on `curl` trace - no any 301 code at all - see in the [curl-to-cat.log](https://github.com/bakito/adguardhome-sync/files/7996532/curl-to-cat.log) and [curl-to-two.log](https://github.com/bakito/adguardhome-sync/files/7996533/curl-to-two.log).
The same with `wget` (not posted here)

**Expected behavior**
Replication is working

**Log Files**
[from-two-to-cat.log](https://github.com/bakito/adguardhome-sync/files/7996530/from-two-to-cat.log)
[from-cat-to-two.log](https://github.com/bakito/adguardhome-sync/files/7996531/from-cat-to-two.log)

**Additional context**
P.S. DNS names is changed, but it doesn't matter - it's official DNS and Let's Encrypt certs.

**Comment by bakito** [comment]
Hi @PeterVoronov 

I found the possible reason, as the client is setup be default with a NoRedirectPolicy which generates this error message.

Could you please try the latest main tag `docker pull ghcr.io/bakito/adguardhome-sync:main`  once this build is finished?
https://github.com/bakito/adguardhome-sync/actions/runs/1791158499

**Comment by petrovoronov** [comment]
> Hi @PeterVoronov
> 
> I found the possible reason, as the client is setup be default with a NoRedirectPolicy which generates this error message.
> 
> Could you please try the latest main tag `docker pull ghcr.io/bakito/adguardhome-sync:main` once this build is finished? https://github.com/bakito/adguardhome-sync/actions/runs/1791158499
> 
> And set env var REDIRECT_POLICY_NO_OF_REDIRECTS to some integer value
> 
> This should change the redirect policy

As I can see - with  REDIRECT_POLICY_NO_OF_REDIRECTS=2 it's working. Thanks.

But for me it's still unclear, how it's identified these redirects ....

**Comment by PeterVoronov** [comment]
> Hi @PeterVoronov
> 
> I found the possible reason, as the client is setup be default with a NoRedirectPolicy which generates this error message.
> 
> Could you please try the latest main tag `docker pull ghcr.io/bakito/adguardhome-sync:main` once this build is finished? https://github.com/bakito/adguardhome-sync/actions/runs/1791158499
> 
> And set env var REDIRECT_POLICY_NO_OF_REDIRECTS to some integer value
> 
> This should change the redirect policy

Thanks. 
It's now working. With REDIRECT_POLICY_NO_OF_REDIRECTS = 2.

P.S. I still don't understand, how this 2 redirects is counted...

**Comment by bakito** [comment]
The redirect could be triggered, because you are running behind traefik, since this is what a reverse proxy does - > redirect to a different service.

This NoRedirectPolicy that is currently used was implemented with the AUTOSETUP feauture, where adguardhome-sync sets up the replicas from scratch. If adguardhome is not setup it redirects all requests to the index.html page. By disabling the redirect this app can evaluate if the replica need to be initialized or not.

Do you  use AUTOSETUP?

If not I could just disable the NoRedirectPolicy if AUTOSETUP is disabled.

**Comment by bakito** [comment]
I released an alpha image ghcr.io/bakito/adguardhome-sync:v0.4.3-alpha does this work also for you?

**Comment by PeterVoronov** [comment]
> The redirect could be triggered, because you are running behind traefik, since this is what a reverse proxy does - > redirect to a different service.
> 
> This NoRedirectPolicy that is currently used was implemented with the AUTOSETUP feauture, where adguardhome-sync sets up the replicas from scratch. If adguardhome is not setup it redirects all requests to the index.html page. By disabling the redirect this app can evaluate if the replica need to be initialized or not.
> 
> Do you use AUTOSETUP?
> 
> If not I could just disable the NoRedirectPolicy if AUTOSETUP is disabled.

The replica had initial manual setup. so I didn't used AUTOSETUP.

**Comment by PeterVoronov** [comment]
> > The redirect could be triggered, because you are running behind traefik, since this is what a reverse proxy does - > redirect to a different service.
> > This NoRedirectPolicy that is currently used was implemented with the AUTOSETUP feauture, where adguardhome-sync sets up the replicas from scratch. If adguardhome is not setup it redirects all requests to the index.html page. By disabling the redirect this app can evaluate if the replica need to be initialized or not.
> > Do you use AUTOSETUP?
> > If not I could just disable the NoRedirectPolicy if AUTOSETUP is disabled.
> 
> The replica had initial manual setup. so I didn't used AUTOSETUP.

I had an error
2022-02-04T22:47:07.134Z        ERROR   sync    sync/sync.go:193        Error getting replica status    {"from": "adguard-two.my.org", "to": "adguard-cat.my.org", "error": "403 Forbidden"}
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).syncTo
        /go/src/app/pkg/sync/sync.go:193
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
        /go/src/app/pkg/sync/sync.go:177
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func3
        /go/src/app/pkg/sync/sync.go:61

When I returned to previous image - everything is working again.

**Comment by bakito** [comment]
I released the first version (with env var  REDIRECT_POLICY_NO_OF_REDIRECTS) as version v0.4.3
