### ISSUE TITLE
Unable to get to run on server start

### ISSUE THREAD

**Issue by mrdeadlocked** [bakito/adguardhome-sync#68]
I installed using the go install method. I have my yaml config setup and working and can run 'adguardhome-sync run' and everything syncs. I tried running the adguardhome-sync run --cron "*/10 * * * *" command and then rebooting and my instances never sync. What am I missing?

**Comment by bakito** [comment]
--cron does not install adguardhome-sync as a system cronjob. It is meant to run in a docker container where the binary is started automatically. 
If you want to run the binary on your bare system, wou need to make sure it is started on system startup.

**Comment by mrdeadlocked** [comment]
Okay. I will have to try and figure out how the best way to get it to run at start.

**Comment by bakito** [comment]
Did you try the systemd setup?
https://github.com/bakito/adguardhome-sync/tree/main/systemd

**Comment by mrdeadlocked** [comment]
@bakito  that did work for me. thanks! I just had to make the working directory listed in the systemd file.
