### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by nknab** [bakito/adguardhome-sync#77]
When I run AdGuard Home, I keep getting a 403 Error

`2022-06-11T10:46:00.010+0200	DEBUG	client	client/client.go:126	do get	{"host": "192.169.0.140:3000", "method": "GET", "path": "status"}
2022-06-11T10:46:00.012+0200	DEBUG	client	client/client.go:138	got response	{"host": "192.169.0.140:3000", "method": "GET", "path": "status", "status": 403, "body": "Forbidden"}
2022-06-11T10:46:00.012+0200	ERROR	sync	sync/sync.go:99	Error getting origin status	{"from": "192.169.0.140:3000", "error": "403 Forbidden"}
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
	/home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:99
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func2
	/home/bakito/go/src/github.com/bakito/adguardhome-sync/pkg/sync/sync.go:44
github.com/robfig/cron/v3.FuncJob.Run
	/home/bakito/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136
github.com/robfig/cron/v3.(*Cron).startJob.func1
	/home/bakito/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:312`

**Comment by bakito** [comment]
@nknab please provide all information requested in the issue template. https://github.com/bakito/adguardhome-sync/issues/new?assignees=&labels=&template=bug_report.md&title=

**Comment by BartKoppers** [comment]
@nknab : maybe it's a simple typo? 192.169.0.140 is a non-local address....
