### ISSUE TITLE
Using special characters in AGH password gives 403 error

### ISSUE THREAD

**Issue by RemcoSchrijver** [bakito/adguardhome-sync#82]
**Describe the bug**
Using special characters in your AGH password results in the sync tool to get a 403 forbidden error.

**To Reproduce**
1. What version of AdGuardHome sync used?
v 0.4.3
2. What version of AdGuardHome is used?
v 0.107.7
3. How does the configuration look? (Anonimized some parts of the password)
      ORIGIN_PASSWORD: "ho**********k^CvvZ^eo2g"
      ORIGIN_URL: "http://192.168.1.5:3000"
      ORIGIN_USERNAME: "User"
      REPLICA_URL: "http://192.168.1.7"
      REPLICA_USERNAME: "User"
      REPLICA_PASSWORD: "e%nSe&E***********s#FfftS&UxB&"
      REPLICA1_AUTOSETUP: false
      CRON: "*/10 * * * *" # run every 10 minutes
      RUNONSTART: true
      LOG_LEVEL: "debug"
4. What is the error message?
When trying to use this config I get a 403 forbidden on the origin, so I then moved to using a password using only alphanumerical characters on the origin and then the whole system functioned properly. Because the replica has some special characters too and that just works I suspect the ^ character to be the culprit

**Expected behavior**
To connect properly to the instance and start syncing with every password regardless of characters included.

**Comment by bakito** [comment]
Hi @RemcoSchrijver 

I was not able to reproduce the issue you describe.

How do you use/start adguardhome-sync? (docker, docker-compose, native)
What kind of config do you use? (env vars /  yaml)

**Comment by RemcoSchrijver** [comment]
Hi @bakito 

Thank you for having a look, I use docker-compose with env vars and using the dictionary notation instead of the list notation such that I can use quotes.

(Using list notation without quotes does not make it work either)

**Comment by bakito** [comment]
can you try to use single quotes instead of double quotes?
I suspect, that something in the string is interpreted as a variable, by docker compose.

**Comment by RemcoSchrijver** [comment]
I'll have a look at that tomorrow, but I do think it's indeed on docker-compose. Read through the spec https://github.com/compose-spec/compose-spec/blob/master/spec.md but it remains a bit vague on it's behaviour with quotes. 

If it's indeed single quotes maybe it would be a good idea to change the compose example to include those single quotes?

**Comment by Lissy93** [comment]
This is a "feature" of YAML's flow scalar's rather than an issue with this repo or docker-compose.

For reference:
- **Double-Quoted**: (`"`), YAML will try and parse escape sequences (e.g. `\n` → inserts line feed character).
- **Single-Quoted**: (`'`) Almost all characters are accepted, and will not be parsed.
- **Plain Style** - Without quotes, YAML will infer data type, only a restricted character set is allowed, and there is no escaping

For more info, see: [YAML Spec → Flow Scalar Styles](https://yaml.org/spec/1.2.2/#73-flow-scalar-styles).
