### ISSUE TITLE
DNS Server list gets sorted

### ISSUE THREAD

**Issue by adamus1red** [bakito/adguardhome-sync#84]
**Describe the bug**
On sync the DNS server list is alphabetically sorted which makes the comments useless.

**To Reproduce**
1. Adguardhome-sync v0.4.3 docker container
2. AdGuardHome v0.107.8 : LXC container to Docker container.

DNS server list on AdGuard main:
```
# Global requests
https://security.cloudflare-dns.com/dns-query
# Home Lookups
[/lan/]10.100.255.1
[/home.lan/]10.100.255.1
# Offsite Larkhall
[/offsite.lan/]192.168.1.1
```

DNS Server list post sync on offsite Adguard
```
# Global requests
# Home Lookups
# Offsite Larkhall
[/lan/]10.100.255.1
[/home.lan/]10.100.255.1
[/offsite.lan/]192.168.1.1
https://security.cloudflare-dns.com/dns-query
```

**Expected behavior**
DNS servers to maintain the order they are entered on the main AdGuard server so the comments match.

**Comment by bakito** [comment]
hi @adamus1red 
Thank you for the finding.

I could fix it in release v0.4.4 which is currently being released.
