### ISSUE TITLE
How can I check which my current version is?

### ISSUE THREAD

**Issue by hawkeye73** [bakito/adguardhome-sync#85]
I tried to update to 0.4.4. but I don't know where to look of the actual version running in indeed 0.4.4. . Any help appreciated.

**Comment by bakito** [comment]
Hi @hawkeye73 

The version is printed, when you run the tool:

`2022-07-24T16:16:24.617Z	INFO	sync	sync/sync.go:30	AdGuardHome sync	{"version": "v0.4.4", "build": "2022-07-23T09:07:46Z"}`

**Comment by hawkeye73** [comment]
I tried and I get the message: No menu item 'sync/sync.go:30' in node '(coreutils.info.gz)sync invocation' 

I'm using Ubuntu 22.04 LTS

**Comment by bakito** [comment]
@hawkeye73 how is adguardhome sync installed?
Do you use the docker image?

**Comment by hawkeye73** [comment]
> @hawkeye73 how is adguardhome sync installed?
> Do you use the docker image?

I installed it on an Ubuntu server. Its a VM. It is working fine. Just wanted to check its current installed version.

**Comment by bakito** [comment]
In the current versions, the app version is only shown in the log, when the sync starts.
In the next release a version option is added to the binary.

**Comment by hawkeye73** [comment]
Thanks for the update!

**Comment by bakito** [comment]
@hawkeye73 I released a new version https://github.com/bakito/adguardhome-sync/releases/tag/v0.4.5

Now you can check the application version with `adguardhome-sync -v`
