### ISSUE TITLE
Debian 11: hangs on Setup cronjob step

### ISSUE THREAD

**Issue by gawainXX** [bakito/adguardhome-sync#88]
I've migrated from AlmaLinux to Debian 11 and AdGuardHome sync works with the exception that if configured to setup a cron task, it will hang up indefinitely.
Snippet from my .adguardhome-sync.yaml file
`# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "*/10 * * * *"`

Then upon running the command to run adguard home it'll hang
`~/work/bin/adguardhome-sync run`

Once it gets to this line it'll hang indefinately;

2022-08-11T23:12:19.211-0700    INFO    sync    sync/sync.go:50 Setup cronjob   {"cron": "*/10 * * * *"}

Go was installed using the process on this page,
https://www.digitalocean.com/community/tutorials/how-to-install-go-on-debian-10
Is perhaps the path throwing things off?

I've commented the cron line out of the config file and manually setup a crontab for the time being but would like to figure out what the root issue is.

**Comment by bakito** [comment]
Hi @gawainXX 

1. adguardhome-sync is built as a static  binary, therefore you do not need go to be installed.
2. please provide more information. How is the config, what are the logs.

**Comment by gawainXX** [comment]
I'm seeing the same behavior with ubuntu 20.04 using the static binary
I've created the ~/.adguardhome-sync.yaml file as instructed,
Here was how I installed adguardhome-sync (was placed into root of ~
`
cd ~

wget --no-check-certificate --content-disposition https://github.com/bakito/adguardhome-sync/releases/download/v0.4.5/adguardhome-sync_0.4.5_linux_x86_64.tar.gz
tar -xf adguardhome-sync_0.4.5_linux_x86_64.tar.gz
chmod +x ~/adguardhome-sync
`


`
2022-08-12T17:32:06.786-0700    INFO    root    cmd/root.go:118 Using config file:/home/adguardhome-sync/.adguardhome-sync.yaml
2022-08-12T17:32:06.788-0700    INFO    sync    sync/sync.go:30 AdGuardHome sync        {"version": "0.4.5", "build": "2022-08-12T07:20:12Z"}
2022-08-12T17:32:06.789-0700    INFO    sync    types/features.go:70    Disabled features       {"features": ["DHCP.ServerConfig", "DHCP.StaticLeases"]}
2022-08-12T17:32:06.789-0700    INFO    sync    sync/sync.go:50 Setup cronjob   {"cron": "*/10 * * * *"}
`

**Comment by bakito** [comment]
PLEASE provide your config file!

**Comment by gawainXX** [comment]
> PLEASE provide your config file!
Username and PW omitted
Works fine if I comment out the cron line.


`# cron expression to run in daemon mode. (default; "" = runs only once)
cron: "*/10 * * * *"

# runs the synchronisation on startup
runOnStart: true

origin:
  # url of the origin instance
  url: http://192.168.4.3
  # apiPath: define an api path if other than "/control"
  # insecureSkipVerify: true # disable tls check
  username: myusername
  password: password

# replica instance (optional, if only one)
replica:
  # url of the replica instance
  url: http://192.168.4.4
  username: myusername
  password: password


# Configure the sync API server, disabled if api port is 0
api:
  # Port, default 8080
  port: 0
  # if username and password are defined, basic auth is applied to the sync API
  username: myusername
  password: password

# Configure sync features; by default all features are enabled.
features:
  generalSettings: true
  queryLogConfig: true
  statsConfig: true
  clientSettings: true
  services: true
  filters: true
  dhcp:
    serverConfig: false
    staticLeases: false
  dns:
    serverConfig: true
    accessLists: true
    rewrites: true
'

**Comment by bakito** [comment]
Hi @gawainXX 

I was not able to reproduce your issue.

I started a debian:11.4 docker container and started adguardhome-sync with your configuration.
The synchronization got started the next time the cron expression matches.

Since your config hast the cron expression  "*/10 * * * *", this will be every 10 minutes. (x:00, x:10, x:20, ...)

**Comment by bakito** [comment]
If you want to start it immediately, you need to add the following parameter:

`runOnStart: true`
