### ISSUE TITLE
Stop-Sleep-Start all instances

### ISSUE THREAD

**Issue by kuubus** [bakito/adguardhome-sync#90]
Could you add a feature to your project that disables all instances for a set period of time and then re-enables them?

That would be a really useful feature.

**Comment by bakito** [comment]
Hi @kuubus 

Please be more specific.
What do you mean by disable the instances?
How would you achieve and trigger this?


Cheers Marc

**Comment by kuubus** [comment]
I mean a function that can start, stop and pause all instances of Adguard Home by URL+Token (API) for a certain time.

**Comment by bakito** [comment]
What do you mean by start stop the instances?
If you stop a instance there is no api that is listening any more.
This would have to be done with a cro job on the machine itself.

**Comment by yurividal** [comment]
He probably reffers to the "disable protection" function on the adguardhome page. I honestly think the time-dependent adguard should be a feature request to AdguardHome, not to this sync tool....

**Comment by bakito** [comment]
@yurividal I totally agree

**Comment by yurividal** [comment]
@kuubus you shoud be able to easily accomplish this with a simple curl command to the agh api. Put it in a cron and you have your automated on/off. =).

Still, perhaps suggest the feature on AGH repo
