### ISSUE TITLE
Sync Fails: 400 Bad Request

### ISSUE THREAD

**Issue by yurividal** [bakito/adguardhome-sync#95]
**Describe the bug**
Sync fails. Used to work fine.
````
2022-09-07T06:30:10.394Z	ERROR	sync	sync/sync.go:240	Error syncing clients	{"from": "10.10.10.2:8081", "to": "10.10.10.5:8081", "error": "400 Bad Request"}
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).syncTo
	/go/src/app/pkg/sync/sync.go:240
github.com/bakito/adguardhome-sync/pkg/sync.(*worker).sync
	/go/src/app/pkg/sync/sync.go:179
github.com/bakito/adguardhome-sync/pkg/sync.Sync.func2
	/go/src/app/pkg/sync/sync.go:44
github.com/robfig/cron/v3.FuncJob.Run
	/go/pkg/mod/github.com/robfig/cron/v3@v3.0.1/cron.go:136
github.com/robfig/cron/v3.(*Cron).startJob.func1
````

**To Reproduce**
1. What version of AdGuardHome sync used? Latest docker version
2. What version of AdGuardHome us used?  Version: v0.107.11

**Comment by yurividal** [comment]
Ok, this happened when I renamed one of the Persistent clients on the first AGH. Seems like the sync is unable to rename the client on the second AGH. I solved it by removing the persistent client from both instances, and then adding it again on the AGH1.

This should be looked into, since the expected behaviour would be to rename the client on the second instance too.

**Comment by bakito** [comment]
Hi @yurividal 

Thank you for reporting the error. I could reproduce and fix it.
The fix will be available in https://github.com/bakito/adguardhome-sync/releases/tag/v0.4.6 once the builds are done.

Cheers Marc
